// react_antd/src/pages/university/UniversityView.tsx
import React, {useEffect} from "react";
import {Button, Cascader, Col, DatePicker, Form, Input, Modal, Row} from "antd";
import {University} from "@/types/resp/university";
import type {AreaOption} from "@/types/areaOption.ts";
import areas from "@/locales/area.json";

interface UniversityViewProps {
  visible: boolean;
  viewRow: object;
  onCloseUniversityView: () => void;
}

const UniversityView: React.FC<UniversityViewProps> = ({visible, viewRow, onCloseUniversityView}) => {

  const [form] = Form.useForm<University>();

  const provinceCityAreaOptions: AreaOption[] = areas.provinces

  const onBack = () => {
    onCloseUniversityView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      const provinceCityArea2 = []
      if ('province' in viewRow && typeof viewRow.province === 'string') {
        provinceCityArea2.push(viewRow.province)
      }
      if ('city' in viewRow && typeof viewRow.city === 'string') {
        provinceCityArea2.push(viewRow.city)
      }
      if ('area' in viewRow && typeof viewRow.area === 'string') {
        provinceCityArea2.push(viewRow.area)
      }
      form.setFieldsValue({...viewRow, provinceCityArea: provinceCityArea2});
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"学校信息详情"} open={visible} onCancel={onCloseUniversityView} width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="学校名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="establishmentDate" label="成立日期">
              <DatePicker/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="contactPhone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="email" label="邮箱">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="provinceCityArea" label="省/市/区">
              <Cascader options={provinceCityAreaOptions} fieldNames={{ label: "name", value: "code" }} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="location" label="地址">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={22}>
            <Form.Item name="universityDescription" label="学校简介" labelCol={{span: 3}}>
              <Input.TextArea autoSize={{ minRows: 5, maxRows: 5 }}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default UniversityView;

// angular_ngzorro/src/app/university/university-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {University} from '../../types/resp/University';
import areas from '../../const/area.json';

@Component({
  selector: 'university-view',
  imports: [
    SharedModule
  ],
  templateUrl: './university-view.component.html',
  standalone: true
})
export class UniversityViewComponent implements OnInit {
  universityForm!: FormGroup;
  isVisible: boolean = false
  title: string = '学校信息详情'
  modalWidth: string = MODAL_WIDTH
  provinceCityAreaOptions = areas.provinces;

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.universityForm = this.fb.group({
      name: [''],
      establishmentDate: [''],
      contactPhone: [''],
      email: [''],
      province: [''],
      city: [''],
      area: [''],
      provinceCityArea: [[]],
      location: [''],
      universityDescription: [''],
      createTime: [''],
      modifyTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(university: University) {
    this.isVisible = true
    const provinceCityArea = []
    if (university.province) {
      provinceCityArea.push(university.province)
    }
    if (university.city) {
      provinceCityArea.push(university.city)
    }
    if (university.area) {
      provinceCityArea.push(university.area)
    }
    this.universityForm.patchValue(Object.assign({provinceCityArea: provinceCityArea}, university));
    this.universityForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="universityForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name">学校名称</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="name" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="establishmentDate">成立日期</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="establishmentDate" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="contactPhone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email">邮箱</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="email" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="area">省/市/区</nz-form-label>
            <nz-form-control>
              <nz-cascader [nzOptions]="provinceCityAreaOptions" formControlName="provinceCityArea"
                           nzValueProperty="code" nzLabelProperty="name"></nz-cascader>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="location">地址</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="location" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="universityDescription">学校简介</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="universityDescription" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="modifyTime">最后修改时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="modifyTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
