// v3_el/src/views/university/UniversityList.vue
<template>
  <div class="university-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>学校信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="universityQueryForm" ref="universityQueryFormRef" :rules="rules">
      <el-form-item label="学校名称" prop="name">
        <el-input v-model="universityQueryForm.name" placeholder="请输入学校名称" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="地址" prop="location">
        <el-input v-model="universityQueryForm.location" placeholder="请输入地址" maxlength="255"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="name" label="学校名称"></el-table-column>
      <el-table-column prop="establishmentDate" label="成立日期"></el-table-column>
      <el-table-column prop="contactPhone" label="联系电话"></el-table-column>
      <el-table-column prop="email" label="邮箱"></el-table-column>
      <el-table-column prop="provinceName" label="省"></el-table-column>
      <el-table-column prop="cityName" label="市"></el-table-column>
      <el-table-column prop="areaName" label="区"></el-table-column>
      <el-table-column prop="location" label="地址"></el-table-column>
      <el-table-column label="学校简介">
        <template v-slot="{ row }">
          <div class="ellipsis">
            {{ row.universityDescription }}
          </div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="universityAddVisible" v-if="universityAddVisible" :title="universityAddTitle" :top="dialogTop" :width="dialogWidth">
      <university-add :id="selectedUniversityId" @close-university-add-event="handleCloseUniversityAddEvent" @reset-university-add-event="handleResetUniversityAddEvent">
      </university-add>
    </el-dialog>
    <el-dialog v-model="universityViewVisible" v-if="universityViewVisible" title="学校信息详情" :top="dialogTop" :width="dialogWidth">
      <university-view :id="selectedUniversityId" @close-university-view-event="handleCloseUniversityViewEvent">
      </university-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref, inject, toRefs} from 'vue';
import universityApi from '@/api/universityApi'
import type {UniversityQueryForm} from "@/types/req/universityQueryForm";
import type {University} from "@/types/resp/university";
import {ElMessage, ElMessageBox, type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";
import UniversityAdd from "@/views/university/UniversityAdd.vue"
import UniversityView from "@/views/university/UniversityView.vue"

const universityQueryFormRef = ref<FormInstance | null>(null);
let universityQueryForm = reactive<UniversityQueryForm>({
  name: '',
  location: '',
})

const state = reactive({
  loading: false,
  tableData: [] as University[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedUniversityId = ref<number>(0)
const universityAddVisible = ref<boolean>(false)
const universityViewVisible = ref<boolean>(false)
const universityAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<University>> = await universityApi.find(universityQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<University> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (universityQueryFormRef.value) {
    universityQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedUniversityId.value = 0
  universityAddVisible.value = true
  universityAddTitle.value = '学校信息新增'
}
const editRow = (id: number) => {
  selectedUniversityId.value = id
  universityAddVisible.value = true
  universityAddTitle.value = '学校信息编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    universityApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedUniversityId.value = id
  universityViewVisible.value = true
}


const handleCloseUniversityViewEvent = () => {
  universityViewVisible.value = false
}

const handleResetUniversityAddEvent = () => {
  universityAddTitle.value = '学校信息新增'
}

const handleCloseUniversityAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  universityAddVisible.value = false
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/university/university-list.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {UniversityService} from '../../service/university.service';
import {UniversityQueryForm} from '../../types/req/UniversityQueryForm';
import {SharedModule} from '../shared.module';
import {University} from '../../types/resp/University';
import {Page} from '../../types/page';
import {UniversityAddComponent} from './university-add.component';
import {UniversityViewComponent} from './university-view.component';
import {NzModalService} from 'ng-zorro-antd/modal';

@Component({
  selector: 'university-list',
  imports: [
    UniversityAddComponent,
    UniversityViewComponent,
    SharedModule
  ],
  templateUrl: './university-list.component.html',
  standalone: true
})
export class UniversityListComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: University[] = [];
  total: number = 0

  @ViewChild(UniversityAddComponent, { static: false }) universityAddComponent!: UniversityAddComponent;
  @ViewChild(UniversityViewComponent, { static: false }) universityViewComponent!: UniversityViewComponent;

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private universityService: UniversityService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      name: [''],
      location: [''],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.universityService.find(new UniversityQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<University> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onAdd() {
    this.universityAddComponent.display(0)
  }

  editRow(id: number) {
    this.universityAddComponent.display(id)
  }

  delRow(id: number) {
    this.modal.confirm({
      nzTitle: '<i>删除提示</i>',
      nzContent: '<b>确定要删除吗?</b>',
      nzOnOk: () => {
        this.universityService.del(id).subscribe({
          next: (resp) => {
            if (resp && resp.code === 1) {
              this.message.success('删除成功!')
              this.onSearch()
            } else {
              this.message.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          },
          complete: () => {
            this.searchLoading = false
          }
        })
      }
    });
  }

  detailRow(record: University) {
    this.universityViewComponent.display(record)
  }

  onAdded(addedFlag: boolean) {
    if (addedFlag) {
      this.onSearch()
    }
  }
}

<nz-breadcrumb class="breadcrumb">
  <nz-breadcrumb-item>
    <a routerLink="/Home">主页</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>学校信息列表</nz-breadcrumb-item>
</nz-breadcrumb>
<form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
  <nz-form-item>
    <nz-form-label nzFor="name">学校名称</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="name" placeholder="请输入学校名称" />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="location">地址</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="location" placeholder="请输入地址" />
    </nz-form-control>
  </nz-form-item>
  <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
  <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
  <button nz-button type="button" class="margin-button" nzType="primary" (click)="onAdd()">新增</button>
</form>
<nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
  <thead>
    <tr>
      <th>学校名称</th>
      <th>成立日期</th>
      <th>联系电话</th>
      <th>邮箱</th>
      <th>省</th>
      <th>市</th>
      <th>区</th>
      <th>地址</th>
      <th>学校简介</th>
      <th nzWidth="250px">操作</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let data of basicTable.data">
      <td>{{data.name}}</td>
      <td>{{data.establishmentDate}}</td>
      <td>{{data.contactPhone}}</td>
      <td>{{data.email}}</td>
      <td>{{data.provinceName}}</td>
      <td>{{data.cityName}}</td>
      <td>{{data.areaName}}</td>
      <td>{{data.location}}</td>
      <td class="ellipsis">{{data.universityDescription}}</td>
      <td>
        <button nz-button type="button" nzType="primary" (click)="editRow(data.id)">编辑</button>
        <button nz-button type="button" nzDanger class="margin-button" (click)="delRow(data.id)">删除</button>
        <button nz-button type="button" class="margin-button" (click)="detailRow(data)">详情</button>
      </td>
    </tr>
  </tbody>
</nz-table>
<university-add (addedEvent)="onAdded($event)"></university-add>
<university-view></university-view>
