// react_antd/src/pages/student/StudentAdd.tsx
import React, {useEffect, useState} from "react";
import {
  Button,
  Cascader,
  CascaderProps,
  Col,
  DatePicker,
  Form,
  Input,
  InputNumber,
  message,
  Modal,
  Row,
  Select
} from "antd";
import type {Result} from "@/types/result";
import studentApi from "@/api/studentApi.ts";
import {Student} from "@/types/resp/student";
import MajorSelector from "@/pages/major/MajorSelector.tsx";
import type {AreaOption} from "@/types/areaOption.ts";
import areas from "@/locales/area.json";

interface StudentAddProps {
  visible: boolean;
  id: number;
  onCloseStudentAdd: () => void;
}

const StudentAdd: React.FC<StudentAddProps> = ({visible, id, onCloseStudentAdd}) => {

  const [form] = Form.useForm<Student>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    studentNumber: [
      { required: true, message: '请输入学号' }
    ],
    name: [
      { required: true, message: '请输入姓名' }
    ],
    password: [
      { required: true, message: '请输入密码' }
    ],
    gender: [
      { required: true, message: '请输入性别' }
    ],
    birthDate: [
      { required: true, message: '请输入出生日期' }
    ],
    majorName: [
      { required: true, message: '请输入专业名称' }
    ],
    grade: [
      { required: true, message: '请输入年级' }
    ],
    contactPhone: [
      { required: true, message: '请输入联系电话' }
    ],
    email: [
      { required: true, message: '请输入邮箱' }
    ],
  };

  let studentForm: Partial<Student> = {}

  const [title, setTitle] = useState('新增学生信息');

  const provinceCityAreaOptions: AreaOption[] = areas.provinces

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑学生信息')
      initStudentFormById(id)
    } else {
      setTitle('新增学生信息')
      form.resetFields();
    }
  }, [visible]);

  const initStudentFormById = async (id: number) => {
    const resp: Result<Student> = await studentApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      studentForm = resp.data
      const provinceCityArea2 = []
      if (studentForm.province) {
        provinceCityArea2.push(studentForm.province)
      }
      if (studentForm.city) {
        provinceCityArea2.push(studentForm.city)
      }
      if (studentForm.area) {
        provinceCityArea2.push(studentForm.area)
      }
      form.setFieldsValue({...studentForm, provinceCityArea: provinceCityArea2});
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let student2Save:Student = form.getFieldsValue()
      if (id) {
        student2Save = Object.assign(studentForm, student2Save)
      }
      const resp: Result<void> = await studentApi.save(student2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增学生信息')
    form.resetFields();
  };
  
  const [majorSelectorVisible, setMajorSelectorVisible] = useState(false);
  const findMajor = () => {
    setMajorSelectorVisible(true);
  }
  const handleMajorSelected = (selectedMajor: { majorId?: number; majorName?: string; }) => {
    setMajorSelectorVisible(false)
    if (selectedMajor && 'majorId' in selectedMajor) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      majorId: selectedMajor['majorId'],
      majorName: selectedMajor['majorName'],
      }));
    }
  };
  const handleCloseMajorSelector = () => {
    setMajorSelectorVisible(false)
  };

  const onBack = () => {
    onCloseStudentAdd()
  };

  const onAreaChange: CascaderProps<AreaOption>['onChange'] = (value) => {
    if (value && value.length > 0 && typeof value[0] === 'string') {
      studentForm.province = value[0]
    }
    if (value && value.length > 1 && typeof value[1] === 'string') {
      studentForm.city = value[1]
    }
    if (value && value.length > 2 && typeof value[2] === 'string') {
      studentForm.area = value[2]
    }
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseStudentAdd} width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="studentForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="studentNumber" label="学号" rules={rules.studentNumber}>
              <Input maxLength={20} placeholder="请输入学号"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="name" label="姓名" rules={rules.name}>
              <Input maxLength={64} placeholder="请输入姓名"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="password" label="密码" rules={rules.password}>
              <Input maxLength={255} placeholder="请输入密码"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="gender" label="性别" rules={rules.gender}>
              <Select placeholder="请选择性别" options={[
                { value: 1, label: <span>男</span> },
                { value: 2, label: <span>女</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="birthDate" label="出生日期" rules={rules.birthDate}>
              <DatePicker/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="majorName" label="专业名称" rules={rules.majorName}>
              <Input.Search placeholder="请选择专业名称" onSearch={findMajor} readOnly={true} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="grade" label="年级" rules={rules.grade}>
              <InputNumber min={2000} max={2100} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="contactPhone" label="联系电话" rules={rules.contactPhone}>
              <Input maxLength={64} placeholder="请输入联系电话"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="email" label="邮箱" rules={rules.email}>
              <Input maxLength={64} placeholder="请输入邮箱"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="provinceCityArea" label="省/市/区">
              <Cascader options={provinceCityAreaOptions} fieldNames={{ label: "name", value: "code" }} onChange={onAreaChange} placeholder="请选择省/市/区" />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="address" label="家庭地址">
              <Input maxLength={255} placeholder="请输入家庭地址"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="enrollmentDate" label="入学日期">
              <DatePicker/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="graduationDate" label="毕业日期">
              <DatePicker/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
      <MajorSelector visible={majorSelectorVisible} onMajorSelected={handleMajorSelected} onCloseMajorSelector={handleCloseMajorSelector} />
    </Modal>
  )
}

export default StudentAdd;

// v2_el/src/views/student/StudentAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="studentForm" :label-width="formLabelWidth" ref="refStudentForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="学号" prop="studentNumber">
            <el-input v-model="studentForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="studentForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="密码" prop="password">
            <el-input v-model="studentForm.password" placeholder="请输入密码" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="性别" prop="gender">
            <el-select v-model="studentForm.gender" placeholder="请选择性别">
              <el-option label="男" :value="1"></el-option>
              <el-option label="女" :value="2"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="出生日期" prop="birthDate">
            <el-date-picker
                v-model="studentForm.birthDate" type="date" placeholder="出生日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="专业名称" prop="majorName">
            <el-input v-model="studentForm.majorName" placeholder="请选择专业名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findMajor"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="年级" prop="grade">
            <el-input-number v-model="studentForm.grade" :min="2000" :max="2100"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="contactPhone">
            <el-input v-model="studentForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="邮箱" prop="email">
            <el-input v-model="studentForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="省/市/区">
            <el-cascader
                v-model="provinceCityArea"
                :options="provinceCityAreaOptions"
                :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"
                @change="handleChange"></el-cascader>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="家庭地址" prop="address">
            <el-input v-model="studentForm.address" placeholder="请输入家庭地址" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="入学日期" prop="enrollmentDate">
            <el-date-picker
                v-model="studentForm.enrollmentDate" type="date" placeholder="入学日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="毕业日期" prop="graduationDate">
            <el-date-picker
                v-model="studentForm.graduationDate" type="date" placeholder="毕业日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script>
import studentApi from '@/api/studentApi'
import MajorSelector from "@/views/major/MajorSelector.vue";
import areas from "@/locales/area.json";
export default {
  name: 'StudentAdd',
  components: {MajorSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      studentForm: {
        studentNumber: '',
        name: '',
        password: '',
        gender: '',
        birthDate: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: '',
        email: '',
        province: '',
        city: '',
        area: '',
        address: '',
        enrollmentDate: '',
        graduationDate: ''
      },
      rules: {
        studentNumber: [
          { required: true, message: '请输入学号', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '请输入密码', trigger: 'blur' }
        ],
        gender: [
          { required: true, message: '请输入性别', trigger: 'blur' }
        ],
        birthDate: [
          { required: true, message: '请输入出生日期', trigger: 'blur' }
        ],
        majorName: [
          { required: true, message: '请输入专业名称', trigger: 'blur' }
        ],
        grade: [
          { required: true, message: '请输入年级', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        email: [
          { required: true, message: '请输入邮箱', trigger: 'blur' }
        ],
      },
      majorSelectorVisible: false,
      provinceCityArea: [],
      provinceCityAreaOptions: areas.provinces
    }
  },
  created () {
    if (this.id) {
      studentApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.studentForm = resp.data
            this.provinceCityArea = []
            if (this.studentForm.province) {
              this.provinceCityArea.push(this.studentForm.province)
            }
            if (this.studentForm.city) {
              this.provinceCityArea.push(this.studentForm.city)
            }
            if (this.studentForm.area) {
              this.provinceCityArea.push(this.studentForm.area)
            }
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.studentForm = {
        studentNumber: '',
        name: '',
        password: '',
        gender: '',
        birthDate: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: '',
        email: '',
        province: '',
        city: '',
        area: '',
        address: '',
        enrollmentDate: '',
        graduationDate: ''
      }
      this.provinceCityArea = []
      this.$emit('reset-student-add-event')
    },
    onSave () {
      this.$refs.refStudentForm.validate((valid) => {
        if (valid) {
          studentApi.save(this.studentForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-student-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findMajor () {
      this.majorSelectorVisible = true
    },
    handleMajorSelectedEvent (selectedMajor) {
      this.majorSelectorVisible = false
      if (selectedMajor && 'majorId' in selectedMajor && this.studentForm.majorId !== selectedMajor['majorId']) {
        this.studentForm.majorId = selectedMajor['majorId']
        this.studentForm.majorName = selectedMajor['majorName']
      }
    },
    handleChange(value) {
      if (value && value.length) {
        this.studentForm.province = value[0]
      }
      if (value && value.length > 1) {
        this.studentForm.city = value[1]
      }
      if (value && value.length > 2) {
        this.studentForm.area = value[2]
      }
    },
    onBack () {
      this.$emit('close-student-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
