// react_antd/src/pages/student/StudentList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, InputNumber, message, Modal, Select, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {Student} from "@/types/resp/student";
import studentApi from '@/api/studentApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import StudentAdd from "@/pages/student/StudentAdd.tsx";
import StudentView from "@/pages/student/StudentView.tsx";
import MajorSelector from "@/pages/major/MajorSelector.tsx";
import {getGenderText} from "@/utils/dictTranslator"
import {exportToExcel} from "@/utils/exportUtil";


const StudentList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '学生信息列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<Student[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Student>> = await studentApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Student> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Student>['columns'] = [
    {title: '学号', dataIndex: 'studentNumber', key: 'studentNumber', width: 60},
    {title: '姓名', dataIndex: 'name', key: 'name', width: 60},
    {title: '密码', dataIndex: 'password', key: 'password', width: 60},
    {title: '性别', key: 'gender', width: 40, render: (_, record) => (
        <span>
        {(function () {
          if (record.gender === 1) return '男';
          else if (record.gender === 2) return '女';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '出生日期', key: 'birthDate', width: 90, render: (_, record) => (
      <div>{record.birthDate.format('YYYY-MM-DD')}</div>
    )},
    {title: '专业名称', dataIndex: 'majorName', key: 'majorName', width: 120},
    {title: '年级', dataIndex: 'grade', key: 'grade', width: 50},
    {title: '联系电话', dataIndex: 'contactPhone', key: 'contactPhone', width: 120},
    {title: '邮箱', dataIndex: 'email', key: 'email', width: 120},
    {title: '省', dataIndex: 'provinceName', key: 'province', width: 100},
    {title: '市', dataIndex: 'cityName', key: 'city', width: 100},
    {title: '区', dataIndex: 'areaName', key: 'area', width: 100},
    {title: '家庭地址', dataIndex: 'address', key: 'address', width: 140},
    {title: '入学日期', key: 'enrollmentDate', width: 90, render: (_, record) => (
      <div>{record.enrollmentDate.format('YYYY-MM-DD')}</div>
    )},
    {title: '毕业日期', key: 'graduationDate', width: 90, render: (_, record) => (
      <div>{record.graduationDate.format('YYYY-MM-DD')}</div>
    )},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [studentAddVisible, setStudentAddVisible] = useState(false);
  const [studentViewVisible, setStudentViewVisible] = useState(false);
  const [selectedStudentId, setSelectedStudentId] = useState(0)
  const [selectedStudent, setSelectedStudent] = useState({})

  const onAdd = () => {
    setSelectedStudentId(0)
    setStudentAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedStudentId(id)
    setStudentAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      studentApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: Student) => {
    setSelectedStudent(record)
    setStudentViewVisible(true)
  };

  const [majorSelectorVisible, setMajorSelectorVisible] = useState(false);
  const findMajor = () => {
    setMajorSelectorVisible(true);
  }
  const handleMajorSelected = (selectedMajor: { majorId?: number; majorName?: string; }) => {
    setMajorSelectorVisible(false)
    if (selectedMajor && 'majorId' in selectedMajor) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      majorId: selectedMajor['majorId'],
      majorName: selectedMajor['majorName'],
      }));
    }
  };
  const handleCloseMajorSelector = () => {
    setMajorSelectorVisible(false)
  };

  const handleCloseStudentAdd = () => {
    setStudentAddVisible(false)
  };

  const handleCloseStudentView = () => {
    setStudentViewVisible(false)
  };

  const onExport = () => {
    const headers = ['学号', '姓名', '性别', '出生日期', '专业名称', '年级', '联系电话', '邮箱', '省', '市', '区', '家庭地址', '入学日期', '毕业日期']
    studentApi.find(form.getFieldsValue()).then(data => {
      if (!data || !data.data || data.data.list.length < 1) {
        messageApi.error('无数据导出')
        return
      }
      const exportData = []
      for (const d of data.data.list) {
        exportData.push([d.studentNumber, d.name, getGenderText(d.gender), d.birthDate, d.majorName, d.grade, d.contactPhone, d.email,
          d.provinceName, d.cityName, d.areaName, d.address, d.enrollmentDate, d.graduationDate])
      }
      exportToExcel(headers, exportData)
    })
  }

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="studentList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="studentNumber" label="学号">
          <Input maxLength={20} placeholder="请输入学号"/>
        </Form.Item>
        <Form.Item name="gender" label="性别">
          <Select placeholder="请选择性别" options={[
            { value: 1, label: <span>男</span> },
            { value: 2, label: <span>女</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item name="majorName" label="专业名称">
          <Input.Search placeholder="请选择专业名称" onSearch={findMajor} readOnly={true} />
        </Form.Item>
        <Form.Item name="grade" label="年级">
          <InputNumber min={2000} max={2100} />
        </Form.Item>
        <Form.Item name="contactPhone" label="联系电话">
          <Input maxLength={64} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onExport}>导出</Button>
        </Form.Item>
      </Form>
      <Table<Student> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                      pagination={{ position: ["bottomCenter"] }}
                      scroll={{ x: 'max-content' }}
                      style={{marginTop: 'var(--container-margin)'}} />
      <MajorSelector visible={majorSelectorVisible} onMajorSelected={handleMajorSelected} onCloseMajorSelector={handleCloseMajorSelector} />
      <StudentAdd visible={studentAddVisible} onCloseStudentAdd={handleCloseStudentAdd} id={selectedStudentId} />
      <StudentView visible={studentViewVisible} onCloseStudentView={handleCloseStudentView} viewRow={selectedStudent} />
    </div>
  );
};

export default StudentList;

// v2_el/src/views/student/StudentList.vue
<template>
  <div class="student-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>学生信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="searchParams">
      <el-form-item label="学号">
        <el-input v-model="searchParams.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
      </el-form-item>
      <el-form-item label="性别" prop="gender">
        <el-select v-model="searchParams.gender" placeholder="请选择性别">
          <el-option label="男" :value="1"></el-option>
          <el-option label="女" :value="2"></el-option>
        </el-select>
      </el-form-item>
      <el-form-item label="专业名称" prop="majorName">
        <el-input v-model="searchParams.majorName" placeholder="请选择专业名称" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findMajor"></i>
        </el-input>
      </el-form-item>
      <el-form-item label="年级" prop="grade">
        <el-input-number v-model="searchParams.grade" :min="2000" :max="2100"></el-input-number>
      </el-form-item>
      <el-form-item label="联系电话">
        <el-input v-model="searchParams.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="pageData.list"
      border
      v-loading="pageData.loading"
      size="mini"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="studentNumber" label="学号" width="80"></el-table-column>
      <el-table-column prop="name" label="姓名" width="80px"></el-table-column>
      <el-table-column prop="password" label="密码" width="90"></el-table-column>
      <el-table-column prop="gender" label="性别" width="50">
        <template v-slot="{ row }">
          <div v-if="row.gender === 1">男</div>
          <div v-if="row.gender === 2">女</div>
        </template>
      </el-table-column>
      <el-table-column prop="birthDate" label="出生日期" width="100"></el-table-column>
      <el-table-column prop="majorName" label="专业名称" width="130"></el-table-column>
      <el-table-column prop="grade" label="年级" width="60"></el-table-column>
      <el-table-column prop="contactPhone" label="联系电话" width="100"></el-table-column>
      <el-table-column prop="email" label="邮箱" width="200"></el-table-column>
      <el-table-column prop="provinceName" label="省" width="70"></el-table-column>
      <el-table-column prop="cityName" label="市" width="70"></el-table-column>
      <el-table-column prop="areaName" label="区" width="70"></el-table-column>
      <el-table-column prop="address" label="家庭地址" width="150"></el-table-column>
      <el-table-column prop="enrollmentDate" label="入学日期" width="100"></el-table-column>
      <el-table-column prop="graduationDate" label="毕业日期" width="100"></el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="paginationChange"
        :current-page="pageData.current"
        :page-sizes="pageData.pageSizes"
        :page-size="pageData.size"
        background
        layout="total, prev, pager, next, jumper"
        :total="pageData.count">
      </el-pagination>
    </div>
    <el-dialog :visible.sync="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentAddVisible" v-if="studentAddVisible" :title="studentAddTitle" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <student-add :id="selectedStudentId" @close-student-add-event="handleCloseStudentAddEvent" @reset-student-add-event="handleResetStudentAddEvent">
      </student-add>
    </el-dialog>
    <el-dialog :visible.sync="studentViewVisible" v-if="studentViewVisible" title="学生信息详情" :top="dialogTop" :width="dialogWidth">
      <student-view :id="selectedStudentId" @close-student-view-event="handleCloseStudentViewEvent">
      </student-view>
    </el-dialog>
  </div>
</template>

<script>
import studentApi from '@/api/studentApi'
import MajorSelector from "@/views/major/MajorSelector.vue";
import StudentAdd from "@/views/student/StudentAdd.vue"
import StudentView from "@/views/student/StudentView.vue"
import listQueryMixin from '@/mixins/listQueryMixin'
import {getGenderText} from "@/utils/dictTranslator";
export default {
  name: 'StudentList',
  components: {MajorSelector,StudentAdd, StudentView},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        studentNumber: '',
        gender: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: ''
      },
      majorSelectorVisible: false,
      studentAddVisible: false,
      studentAddTitle: '',
      studentViewVisible: false,
      selectedStudentId: 0
    }
  },
  methods: {
    getPageData (p) {
      return studentApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        studentNumber: '',
        gender: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    onAdd () {
      this.selectedStudentId = ''
      this.studentAddVisible = true
      this.studentAddTitle = '学生信息新增'
    },
    onExport () {
      const headers = ['学号', '姓名', '性别', '出生日期', '专业名称', '年级', '联系电话', '邮箱', '省', '市', '区', '家庭地址', '入学日期', '毕业日期']
      const params = Object.assign(this.getPaginationParams(), this.searchParams)
      this.getPageData(params).then(data => {
        if (!data || !data.data || data.data.list.length < 1) {
          this.$message.error('无数据导出')
          return
        }
        const exportData = []
        for (const d of data.data.list) {
          exportData.push([d.studentNumber, d.name, getGenderText(d.gender), d.birthDate, d.majorName, d.grade, d.contactPhone, d.email,
            d.provinceName, d.cityName, d.areaName, d.address, d.enrollmentDate, d.graduationDate])
        }
        this.exportToExcel(headers, exportData)
      })
    },
    editRow (id) {
      this.selectedStudentId = id
      this.studentAddVisible = true
      this.studentAddTitle = '学生信息编辑'
    },
    delRow (id) {
      if (!id) {
        return
      }
      this.$confirm('确定要删除吗?', '删除提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        studentApi.del(id)
          .then((resp) => {
            if (resp && resp.code === 1) {
              this.$message.success('删除成功!')
              this.onSearch()
            } else {
              this.$message.error('删除失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          })
          .catch(error => {
            console.error('操作失败:', error)
          })
      }).catch(() => {})
    },
    detailRow (id) {
      this.selectedStudentId = id
      this.studentViewVisible = true
    },
    findMajor () {
      this.majorSelectorVisible = true
    },
    handleMajorSelectedEvent (selectedMajor) {
      this.majorSelectorVisible = false
      if (selectedMajor && 'majorId' in selectedMajor && this.searchParams.majorId !== selectedMajor['majorId']) {
        this.searchParams.majorId = selectedMajor['majorId']
        this.searchParams.majorName = selectedMajor['majorName']
      }
    },
    handleCloseStudentViewEvent () {
      this.studentViewVisible = false
    },
    handleResetStudentAddEvent () {
      this.studentAddTitle = '学生信息新增'
    },
    handleCloseStudentAddEvent (params) {
      if (params && params.search) {
        this.onSearch()
      }
      this.studentAddVisible = false
    }
  }
}
</script>

<style lang="scss">
</style>
