// v2_el/src/views/major/MajorAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="majorForm" :label-width="formLabelWidth" ref="refMajorForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="院系名称" prop="facultyName">
            <el-input v-model="majorForm.facultyName" placeholder="请选择院系名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findFaculty"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="专业名称" prop="name">
            <el-input v-model="majorForm.name" placeholder="请输入专业名称" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="学位类型" prop="degreeType">
            <el-select v-model="majorForm.degreeType" placeholder="请选择学位类型">
              <el-option label="学士" :value="1"></el-option>
              <el-option label="硕士" :value="2"></el-option>
              <el-option label="博士" :value="3"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="学制(年)" prop="duration">
            <el-input-number v-model="majorForm.duration" :min="1" :max="10"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="contactPhone">
            <el-input v-model="majorForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="邮箱" prop="email">
            <el-input v-model="majorForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="办公地点" prop="officeLocation">
            <el-input v-model="majorForm.officeLocation" placeholder="请输入办公地点" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="22">
          <el-form-item label="专业简介" prop="majorDescription">
            <el-input v-model="majorForm.majorDescription" placeholder="请输入专业简介" type="textarea" :rows="5" maxlength="65535"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="facultySelectorVisible" v-if="facultySelectorVisible" title="院系信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <faculty-selector @faculty-selected-event="handleFacultySelectedEvent">
      </faculty-selector>
    </el-dialog>
  </div>
</template>

<script>
import majorApi from '@/api/majorApi'
import FacultySelector from "@/views/faculty/FacultySelector.vue";
export default {
  name: 'MajorAdd',
  components: {FacultySelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      majorForm: {
        facultyId: '',
        facultyName: '',
        name: '',
        degreeType: '',
        duration: '',
        contactPhone: '',
        email: '',
        officeLocation: '',
        majorDescription: ''
      },
      rules: {
        facultyName: [
          { required: true, message: '请输入院系名称', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '请输入专业名称', trigger: 'blur' }
        ],
        degreeType: [
          { required: true, message: '请输入学位类型', trigger: 'blur' }
        ],
        duration: [
          { required: true, message: '请输入学制(年)', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        email: [
          { required: true, message: '请输入邮箱', trigger: 'blur' }
        ],
        officeLocation: [
          { required: true, message: '请输入办公地点', trigger: 'blur' }
        ],
      },
      facultySelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      majorApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.majorForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.majorForm = {
        facultyId: '',
        facultyName: '',
        name: '',
        degreeType: '',
        duration: '',
        contactPhone: '',
        email: '',
        officeLocation: '',
        majorDescription: ''
      }
      this.$emit('reset-major-add-event')
    },
    onSave () {
      this.$refs.refMajorForm.validate((valid) => {
        if (valid) {
          majorApi.save(this.majorForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-major-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findFaculty () {
      this.facultySelectorVisible = true
    },
    handleFacultySelectedEvent (selectedFaculty) {
      this.facultySelectorVisible = false
      if (selectedFaculty && 'facultyId' in selectedFaculty && this.majorForm.facultyId !== selectedFaculty['facultyId']) {
        this.majorForm.facultyId = selectedFaculty['facultyId']
        this.majorForm.facultyName = selectedFaculty['facultyName']
      }
    },
    onBack () {
      this.$emit('close-major-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/major/major-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {MajorService} from '../../service/major.service';
import {SharedModule} from '../shared.module';
import {MajorForm} from '../../types/req/MajorForm';
import {MODAL_WIDTH} from '../../const'
import {FacultySelectorComponent} from '../faculty/faculty-selector.component';

@Component({
  selector: 'major-add',
  imports: [
    FacultySelectorComponent,
    SharedModule
  ],
  templateUrl: './major-add.component.html',
  standalone: true
})
export class MajorAddComponent implements OnInit {
  majorToSave:MajorForm = {};
  majorForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增专业信息'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(FacultySelectorComponent, { static: false }) facultySelectorComponent!: FacultySelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private majorService: MajorService
  ) {}

  ngOnInit(): void {
    this.majorForm = this.fb.group({
      facultyId: [0],
      facultyName: ['', [Validators.required]],
      name: ['', [Validators.required]],
      degreeType: [undefined, [Validators.required]],
      duration: [0, [Validators.required]],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      officeLocation: ['', [Validators.required]],
      majorDescription: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.majorForm.controls) {
        this.majorForm.controls[i].markAsDirty();
        this.majorForm.controls[i].updateValueAndValidity();
      }
      if (!this.majorForm.valid) {
        this.saveLoading = false
        return
      }
      this.majorService.save(Object.assign(this.majorToSave, this.majorForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增专业信息'.slice()
    this.majorForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改专业信息'
      this.saveLoading = true
      this.majorService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.majorToSave = resp.data
            this.majorForm.patchValue(this.majorToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findFaculty() {
    this.facultySelectorComponent.display()
  }

  handleFacultySelectedEvent(selectedFaculty: { facultyId?: number; facultyName?: string; }) {
    if (selectedFaculty && 'facultyId' in selectedFaculty) {
      this.majorForm.patchValue(selectedFaculty);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="majorForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="facultyName" nzRequired>院系名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择院系名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="facultyNameSuffixIconButton">
                <input nz-input formControlName="facultyName" placeholder="请选择院系名称" readonly />
              </nz-input-group>
              <ng-template #facultyNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findFaculty()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>专业名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入专业名称'">
              <input nz-input formControlName="name" placeholder="请输入专业名称" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="degreeType" nzRequired>学位类型</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择学位类型'">
              <nz-select formControlName="degreeType">
                <nz-option nzLabel="学士" [nzValue]="1"></nz-option>
                <nz-option nzLabel="硕士" [nzValue]="2"></nz-option>
                <nz-option nzLabel="博士" [nzValue]="3"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="duration" nzRequired>学制(年)</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入学制(年)'">
            <nz-input-number formControlName="duration" [nzMin]="1" [nzMax]="10" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入邮箱'">
              <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="officeLocation" nzRequired>办公地点</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入办公地点'">
              <input nz-input formControlName="officeLocation" placeholder="请输入办公地点" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="majorDescription">专业简介</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="majorDescription" placeholder="请输入专业简介" maxlength="65535"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<faculty-selector (facultySelectedEvent)="handleFacultySelectedEvent($event)"></faculty-selector>
