// react_antd/src/pages/StudentRegister.tsx
import React, {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import type {Result} from '@/types/result'
import {Button, Cascader, CascaderProps, Col, DatePicker, Form, Input, InputNumber, message, Row, Select} from 'antd';
import Captcha from '@/components/Captcha';
import {useTranslation} from "react-i18next";
import '@/assets/styles/register.css'
import studentApi from "@/api/studentApi.ts";
import MajorSelector from "@/pages/major/MajorSelector.tsx";
import {Student} from "@/types/resp/student";
import type {AreaOption} from "@/types/areaOption.ts";
import areas from "@/locales/area.json";
import {generateCaptcha} from "@/utils/verificationCode.ts";


type MessageType = 'success' | 'warning' | 'error';

// 定义校验规则
const rules = {
  studentNumber: [
    { required: true, message: '请输入学号' }
  ],
  name: [
    { required: true, message: '请输入姓名' }
  ],
  password: [
    { required: true, message: '请输入密码' }
  ],
  password2: [
    { required: true, message: '请确认密码' }
  ],
  gender: [
    { required: true, message: '请输入性别' }
  ],
  birthDate: [
    { required: true, message: '请输入出生日期' }
  ],
  majorName: [
    { required: true, message: '请输入专业名称' }
  ],
  grade: [
    { required: true, message: '请输入年级' }
  ],
  contactPhone: [
    { required: true, message: '请输入联系电话' }
  ],
  email: [
    { required: true, message: '请输入邮箱' }
  ],
  verificationCode: [
    { required: true, message: '验证码不能为空' }
  ]
};

const initialStudentForm: Partial<Student> = {
  gender: 1,
  majorId: 0,
  grade: 2000
}

const StudentRegister: React.FC = () => {
  const navigate = useNavigate();

  const [messageApi, messageContextHolder] = message.useMessage();

  const openNotification = (messageType: MessageType, msg: string, onCloseCallback?: () => void) => {
    messageApi.open({
      type: messageType,
      content: msg,
      duration: 1,
      onClose: () => {
        if (onCloseCallback) {
          onCloseCallback(); // 如果提供了回调，则执行它
        }
      }
    });
  };

  const handleRegisterSuccess = (type: MessageType, msg: string) => {
    openNotification(type, msg, () => {
      navigate(`/Login?type=3` );
    });
  };
  const handleRegisterError = (type: MessageType, msg: string) => {
    openNotification(type, msg);
  };

  const { t } = useTranslation();
  const [form] = Form.useForm();
  const [studentForm] = useState(initialStudentForm)

  const [generatedCaptcha, setGeneratedCaptcha] = useState(generateCaptcha());

  const refreshCaptcha = () => {
    const newCaptcha = generateCaptcha();
    setGeneratedCaptcha(newCaptcha);
  };

  const handleRegister = async () => {
    try {
      await form.validateFields()
      const student2Save:Student = Object.assign(studentForm, form.getFieldsValue())
      if (student2Save.password !== student2Save.password2) {
        messageApi.error('两次输入的密码不一致，请重新输入')
        refreshCaptcha()
        student2Save.password = ''
        student2Save.password2 = ''
        form.setFieldsValue(student2Save);
        return
      }
      if (student2Save.verificationCode && student2Save.verificationCode.toUpperCase() !== generatedCaptcha.toUpperCase()) {
        openNotification('error', '验证码不正确')
        refreshCaptcha()
        student2Save.verificationCode = ''
        form.setFieldsValue(student2Save);
        return
      }

      const resp: Result<void> = await studentApi.save(student2Save)
      if (!resp || resp.code !== 1) {
        const errorMsg = resp && resp.msg ? resp.msg : '操作异常'
        handleRegisterError('error', errorMsg)
        refreshCaptcha()
        return
      }
      handleRegisterSuccess('success', '注册成功')
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    form.resetFields();
  };

  const onBack = () => {
    navigate(`/Login?type=3` );
  }

  const [majorSelectorVisible, setMajorSelectorVisible] = useState(false);
  const findMajor = () => {
    setMajorSelectorVisible(true);
  }
  const handleMajorSelected = (selectedMajor: { majorId?: number; majorName?: string; }) => {
    setMajorSelectorVisible(false)
    if (selectedMajor && 'majorId' in selectedMajor) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
        majorId: selectedMajor['majorId'],
        majorName: selectedMajor['majorName'],
      }));
    }
  };
  const handleCloseMajorSelector = () => {
    setMajorSelectorVisible(false)
  };

  const provinceCityAreaOptions: AreaOption[] = areas.provinces

  const onAreaChange: CascaderProps<AreaOption>['onChange'] = (value) => {
    if (value && value.length > 0 && typeof value[0] === 'string') {
      studentForm.province = value[0]
    }
    if (value && value.length > 1 && typeof value[1] === 'string') {
      studentForm.city = value[1]
    }
    if (value && value.length > 2 && typeof value[2] === 'string') {
      studentForm.area = value[2]
    }
  };

  return (
    <div className="register-page">
      {messageContextHolder}
      <div className="register">
        <div className="login-title">{t('title')}</div>
        <div className="login-subtitle">{t('studentRegisterTitle')}</div>
        <Form form={form} initialValues={initialStudentForm} labelCol={{span: 6}}>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="studentNumber" label="学号" rules={rules.studentNumber}>
                <Input maxLength={20} placeholder="请输入学号"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="name" label="姓名" rules={rules.name}>
                <Input maxLength={64} placeholder="请输入姓名"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="gender" label="性别" rules={rules.gender}>
                <Select placeholder="请选择性别" options={[
                  {value: 1, label: <span>男</span>},
                  {value: 2, label: <span>女</span>}
                ]}/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="password" label="密码" rules={rules.password}>
                <Input maxLength={255} placeholder="请输入密码"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="password2" label="确认密码" rules={rules.password2}>
                <Input maxLength={255} placeholder="请输入确认密码"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="birthDate" label="出生日期" rules={rules.birthDate}>
                <DatePicker/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="majorName" label="专业名称" rules={rules.majorName}>
                <Input.Search placeholder="请选择专业名称" onSearch={findMajor} readOnly={true}/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="grade" label="年级" rules={rules.grade}>
                <InputNumber min={2000} max={2100}/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="enrollmentDate" label="入学日期">
                <DatePicker/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="contactPhone" label="联系电话" rules={rules.contactPhone}>
                <Input maxLength={64} placeholder="请输入联系电话"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="email" label="邮箱" rules={rules.email}>
                <Input maxLength={64} placeholder="请输入邮箱"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="graduationDate" label="毕业日期">
                <DatePicker/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="provinceCityArea" label="省/市/区">
                <Cascader options={provinceCityAreaOptions} fieldNames={{label: "name", value: "code"}}
                          onChange={onAreaChange} placeholder="请选择省/市/区"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="verificationCode" label="验证码" rules={rules.verificationCode}>
                <Input maxLength={6} placeholder="请输入验证码"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Captcha captcha={generatedCaptcha} onRefresh={refreshCaptcha}/>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="address" label="家庭地址">
                <Input maxLength={255} placeholder="请输入家庭地址"/>
              </Form.Item>
            </Col>
          </Row>
        </Form>
        <div className="custom-footer">
          <Button type="primary" onClick={handleRegister}>注册</Button>
          <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
          <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>返回登录</Button>
        </div>
      </div>
      <div className="footer">
        <span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span>
        <a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a>
      </div>
      <MajorSelector visible={majorSelectorVisible} onMajorSelected={handleMajorSelected}
                     onCloseMajorSelector={handleCloseMajorSelector}/>
    </div>
  );
};

export default StudentRegister;

// v2_el/src/views/StudentRegister.vue
<template>
  <div class="register-page">
    <div class="register">
      <div class="login__logo"></div>
      <div class="login__title">{{ $t('title') }}</div>
      <div class="login__subtitle">{{ $t('studentRegisterTitle') }}</div>
      <el-form :model="registerForm" :rules="rules" ref="registerForm" @keyup.enter.native="onRegister" size="medium" :label-width="labelWidth">
        <el-row>
          <el-col :span="8">
            <el-form-item label="学号" prop="studentNumber">
              <el-input v-model="registerForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="registerForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="性别" prop="gender">
              <el-select v-model="registerForm.gender" placeholder="请选择性别">
                <el-option label="男" :value="1"></el-option>
                <el-option label="女" :value="2"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="密码" prop="password">
              <el-input v-model="registerForm.password" type="password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item prop="password2" label="确认密码">
              <el-input v-model="registerForm.password2" type="password" placeholder="请确认确认密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="出生日期" prop="birthDate">
              <el-date-picker
                  v-model="registerForm.birthDate" type="date" placeholder="出生日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="专业名称" prop="majorName">
              <el-input v-model="registerForm.majorName" placeholder="请选择专业名称" readonly="readonly">
                <i slot="suffix" class="el-input__icon el-icon-search" @click="findMajor"></i>
              </el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="年级" prop="grade">
              <el-input-number v-model="registerForm.grade" :min="2000" :max="2100"></el-input-number>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="入学日期" prop="enrollmentDate">
              <el-date-picker
                  v-model="registerForm.enrollmentDate" type="date" placeholder="入学日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="联系电话" prop="contactPhone">
              <el-input v-model="registerForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="registerForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="毕业日期" prop="graduationDate">
              <el-date-picker
                  v-model="registerForm.graduationDate" type="date" placeholder="毕业日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="省" prop="province">
              <el-input v-model="registerForm.province" placeholder="请输入省" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="市" prop="city">
              <el-input v-model="registerForm.city" placeholder="请输入市" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="区" prop="area">
              <el-input v-model="registerForm.area" placeholder="请输入区" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="家庭地址" prop="address">
              <el-input v-model="registerForm.address" placeholder="请输入家庭地址" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item prop="verificationCode" label="验证码">
              <el-input v-model="registerForm.verificationCode" placeholder="请输入验证码"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item>
              <canvas id="captchaCanvas" width="150" height="50" @click="drawCaptcha"></canvas>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" :offset="6">
            <el-button type="primary" @click="onRegister" :loading="loading">注册</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack" :loading="loading">返回登录</el-button>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="footer">
      <span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span><a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a>
    </div>
    <el-dialog :visible.sync="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script>
import studentApi from '@/api/studentApi'
import captchaMixin from "@/mixins/captchaMixin";
import MajorSelector from "@/views/major/MajorSelector.vue";
export default {
  name: 'StudentRegister',
  components: {MajorSelector},
  mixins: [
    captchaMixin
  ],
  data () {
    return {
      registerForm: {
        studentNumber: '',
        name: '',
        password: '',
        password2: '',
        gender: 1,
        birthDate: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: '',
        province: '',
        city: '',
        area: '',
        address: '',
        enrollmentDate: '',
        graduationDate: '',
        verificationCode: ''
      },
      labelWidth: '80px',
      rules: {
        studentNumber: [
          { required: true, message: '学号不能为空', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '姓名不能为空', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '密码不能为空', trigger: 'blur' }
        ],
        password2: [
          { required: true, message: '请确认密码', trigger: 'blur' }
        ],
        birthDate: [
          { required: true, message: '出生日期不能为空', trigger: 'blur' }
        ],
        enrollmentDate: [
          { required: true, message: '入学日期不能为空', trigger: 'blur' }
        ],
        gender: [
          { required: true, message: '请选择性别', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '联系电话不能为空', trigger: 'blur' }
        ],
        verificationCode: [
          { required: true, message: '验证码不能为空', trigger: 'blur' }
        ]
      },
      loading: false,
      majorSelectorVisible: false
    }
  },
  created () {
  },
  methods: {
    onReset () {
      this.registerForm = {
        studentNumber: '',
        name: '',
        password: '',
        password2: '',
        gender: 1,
        birthDate: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: '',
        province: '',
        city: '',
        area: '',
        address: '',
        enrollmentDate: '',
        graduationDate: '',
        verificationCode: ''
      }
      this.provinceCityArea = []
    },
    onRegister () {
      this.$refs.registerForm.validate(async (valid) => {
        if (valid) {
          if (this.registerForm.password !== this.registerForm.password2) {
            this.$message.error('两次输入的密码不一致，请重新输入')
            this.registerForm.password = ''
            this.registerForm.password2 = ''
            this.refreshCaptcha()
            return
          }
          if (this.generatedVerificationCode.toLowerCase() !== this.registerForm.verificationCode.toLowerCase()) {
            this.$message.error('验证码错误')
            this.refreshCaptcha()
            return
          }
          this.loading = true
          // 登录验证
          studentApi.save(this.registerForm)
              .then(data => {
                console.log('data', data)
                if (data.code === 1) {
                  this.$message.success('注册成功')
                  this.$router.push({ path: '/Login', query: {type: 3} })
                } else {
                  this.$message.error('注册失败:' + (data.msg ? data.msg : ''))
                  this.refreshCaptcha()
                  this.loading = false
                }
              })
              .catch(error => {
                console.log('注册失败', error)
                this.$message.error('注册失败')
                this.refreshCaptcha()
                this.loading = false
              })
        } else {
          this.refreshCaptcha()
          return false
        }
      })
    },
    refreshCaptcha () {
      this.registerForm.verificationCode = ''
      this.drawCaptcha()
    },
    findMajor () {
      this.majorSelectorVisible = true
    },
    handleMajorSelectedEvent (selectedMajor) {
      this.majorSelectorVisible = false
      if (selectedMajor && 'majorId' in selectedMajor && this.registerForm.majorId !== selectedMajor['majorId']) {
        this.registerForm.majorId = selectedMajor['majorId']
        this.registerForm.majorName = selectedMajor['majorName']
      }
    },
    onBack () {
      this.$router.push({ name: 'Login', query: {type: 3}})
    }
  }
}
</script>

<style lang="scss">
@import "@/assets/styles/register";
</style>
