// angular_ngzorro/src/app/teacher/teacher-register.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {SharedModule} from '../shared.module';
import areas from '../../const/area.json'
import {CaptchaComponent} from '../captcha/captcha.component';
import {TITLE} from '../../const';
import {TeacherForm} from '../../types/req/TeacherForm';
import {TeacherService} from '../../service/teacher.service';
import {Router} from '@angular/router';
import {FacultySelectorComponent} from '../faculty/faculty-selector.component';

@Component({
  selector: 'teacher-register',
  imports: [
    SharedModule,
    CaptchaComponent,
    FacultySelectorComponent
  ],
  templateUrl: './teacher-register.component.html',
  standalone: true,
  styleUrls: ['../../assets/register.less']
})
export class TeacherRegisterComponent implements OnInit {
  teacherToSave:TeacherForm = {};
  teacherForm!: FormGroup;
  verificationCode: string = '';
  saveLoading: boolean = false
  title: string = TITLE
  teacherRegisterTitle: string = '教师注册'
  provinceCityAreaOptions = areas.provinces;

  @ViewChild(FacultySelectorComponent, { static: false }) facultySelectorComponent!: FacultySelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private teacherService: TeacherService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.teacherForm = this.fb.group({
      facultyId: [0],
      facultyName: ['', [Validators.required]],
      name: ['', [Validators.required]],
      password: ['', [Validators.required]],
      password2: ['', [Validators.required]],
      title: [undefined, [Validators.required]],
      gender: [undefined, [Validators.required]],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      profile: [''],
      verificationCode: ['', [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.teacherForm.controls) {
        this.teacherForm.controls[i].markAsDirty();
        this.teacherForm.controls[i].updateValueAndValidity();
      }
      if (!this.teacherForm.valid) {
        this.saveLoading = false
        return
      }
      const formValue = this.teacherForm.value;
      if (formValue.verificationCode.toLowerCase() !== this.verificationCode.toLowerCase()) {
        this.message.error('验证码错误');
        this.onReset()
        this.saveLoading = false
        return
      }
      this.teacherService.save(Object.assign(this.teacherToSave, formValue)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.router.navigate(['/login'], { queryParams: { type: 2 } })
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.teacherForm.reset()
  }

  onBack() {
    this.router.navigate(['/login'])
  }

  findFaculty() {
    this.facultySelectorComponent.display()
  }

  handleFacultySelectedEvent(selectedFaculty: { facultyId?: number; facultyName?: string; }) {
    if (selectedFaculty && 'facultyId' in selectedFaculty) {
      this.teacherForm.patchValue(selectedFaculty);
    }
  }

  onVerificationCodeGenerated(verificationCode: string): void {
    this.verificationCode = verificationCode
  }
}

<div class="register-page">
  <div class="register">
    <div class="login-title">{{ title }}</div>
    <div class="login-subtitle">{{ teacherRegisterTitle }}</div>
    <form [formGroup]="teacherForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="facultyName" nzRequired>院系名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择院系名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="facultyNameSuffixIconButton">
                <input nz-input formControlName="facultyName" placeholder="请选择院系名称" readonly />
              </nz-input-group>
              <ng-template #facultyNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findFaculty()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="gender" nzRequired>性别</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择性别'">
              <nz-select formControlName="gender">
                <nz-option nzLabel="男" [nzValue]="1"></nz-option>
                <nz-option nzLabel="女" [nzValue]="2"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入密码'">
              <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password2" nzRequired>确认密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请确认密码'">
              <input nz-input formControlName="password2" placeholder="请确认密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="title" nzRequired>职称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择职称'">
              <nz-select formControlName="title">
                <nz-option nzLabel="助教" [nzValue]="1"></nz-option>
                <nz-option nzLabel="讲师" [nzValue]="2"></nz-option>
                <nz-option nzLabel="副教授" [nzValue]="3"></nz-option>
                <nz-option nzLabel="教授" [nzValue]="4"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入邮箱'">
              <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="profile">教师简介</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="profile" placeholder="请输入教师简介" maxlength="65535"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label nzRequired [nzSpan]="4" nzFor="verificationCode">验证码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入验证码'">
              <input nz-input formControlName="verificationCode" placeholder="请输入验证码" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <div class="captcha-container">
              <app-captcha (verificationCodeGenerated)="onVerificationCodeGenerated($event)"></app-captcha>
            </div>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">注册</button>
      <button nz-button nzType="default" class="margin-button" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" class="margin-button" (click)="onBack()">返回登录</button>
    </div>
  </div>
</div>
<faculty-selector (facultySelectedEvent)="handleFacultySelectedEvent($event)"></faculty-selector>

// v2_el/src/views/TeacherRegister.vue
<template>
  <div class="register-page">
    <div class="register">
      <div class="login__logo"></div>
      <div class="login__title">{{ $t('title') }}</div>
      <div class="login__subtitle">{{ $t('teacherRegisterTitle') }}</div>
      <el-form :model="registerForm" :rules="rules" ref="registerForm" @keyup.enter.native="onRegister" size="medium" :label-width="labelWidth">
        <el-row>
          <el-col :span="8">
            <el-form-item label="院系名称" prop="facultyName">
              <el-input v-model="registerForm.facultyName" placeholder="请选择院系名称" readonly="readonly">
                <i slot="suffix" class="el-input__icon el-icon-search" @click="findFaculty"></i>
              </el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="registerForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="性别" prop="gender">
              <el-select v-model="registerForm.gender" placeholder="请选择性别">
                <el-option label="男" :value="1"></el-option>
                <el-option label="女" :value="2"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="密码" prop="password">
              <el-input v-model="registerForm.password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="确认密码" prop="password2">
              <el-input v-model="registerForm.password2" placeholder="请输入确认密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="职称" prop="title">
              <el-select v-model="registerForm.title" placeholder="请选择职称">
                <el-option label="助教" :value="1"></el-option>
                <el-option label="讲师" :value="2"></el-option>
                <el-option label="副教授" :value="3"></el-option>
                <el-option label="教授" :value="4"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="联系电话" prop="contactPhone">
              <el-input v-model="registerForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="registerForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <el-form-item label="教师简介" prop="profile">
              <el-input v-model="registerForm.profile" placeholder="请输入教师简介" maxlength="65535"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item prop="verificationCode" label="验证码">
              <el-input v-model="registerForm.verificationCode" placeholder="请输入验证码"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item>
              <canvas id="captchaCanvas" width="150" height="50" @click="drawCaptcha"></canvas>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" :offset="6">
            <el-button type="primary" @click="onRegister" :loading="loading">注册</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack" :loading="loading">返回登录</el-button>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <el-dialog :visible.sync="facultySelectorVisible" v-if="facultySelectorVisible" title="院系信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <faculty-selector @faculty-selected-event="handleFacultySelectedEvent">
      </faculty-selector>
    </el-dialog>
  </div>
</template>

<script>
import teacherApi from '@/api/teacherApi'
import captchaMixin from "@/mixins/captchaMixin";
import FacultySelector from "@/views/faculty/FacultySelector.vue";
export default {
  name: 'TeacherRegister',
  components: {FacultySelector},
  mixins: [
    captchaMixin
  ],
  data () {
    return {
      registerForm: {
        facultyId: '',
        facultyName: '',
        name: '',
        password: '',
        password2: '',
        title: '',
        gender: 1,
        contactPhone: '',
        email: '',
        profile: '',
        verificationCode: ''
      },
      labelWidth: '80px',
      rules: {
        facultyName: [
          { required: true, message: '院系不能为空', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '姓名不能为空', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '密码不能为空', trigger: 'blur' }
        ],
        password2: [
          { required: true, message: '请确认密码', trigger: 'blur' }
        ],
        title: [
          { required: true, message: '职称不能为空', trigger: 'blur' }
        ],
        gender: [
          { required: true, message: '请选择性别', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '联系电话不能为空', trigger: 'blur' }
        ],
        verificationCode: [
          { required: true, message: '验证码不能为空', trigger: 'blur' }
        ]
      },
      loading: false,
      facultySelectorVisible: false
    }
  },
  created () {
  },
  methods: {
    onReset () {
      this.registerForm = {
        facultyId: '',
        facultyName: '',
        name: '',
        password: '',
        password2: '',
        title: '',
        gender: 1,
        contactPhone: '',
        email: '',
        profile: '',
        verificationCode: ''
      }
    },
    onRegister () {
      this.$refs.registerForm.validate(async (valid) => {
        if (valid) {
          if (this.registerForm.password !== this.registerForm.password2) {
            this.$message.error('两次输入的密码不一致，请重新输入')
            this.registerForm.password = ''
            this.registerForm.password2 = ''
            this.refreshCaptcha()
            return
          }
          if (this.generatedVerificationCode.toLowerCase() !== this.registerForm.verificationCode.toLowerCase()) {
            this.$message.error('验证码错误')
            this.refreshCaptcha()
            return
          }
          this.loading = true
          // 登录验证
          teacherApi.save(this.registerForm)
              .then(data => {
                if (data.code === 1) {
                  this.$message.success('注册成功')
                  this.$router.push({ path: '/Login', query: {type: 2} })
                } else {
                  this.$message.error('注册失败:' + (data.msg ? data.msg : ''))
                  this.refreshCaptcha()
                  this.loading = false
                }
              })
              .catch(error => {
                console.log('注册失败', error)
                this.$message.error('注册失败')
                this.refreshCaptcha()
                this.loading = false
              })
        } else {
          this.refreshCaptcha()
          return false
        }
      })
    },
    refreshCaptcha () {
      this.registerForm.verificationCode = ''
      this.drawCaptcha()
    },
    findFaculty () {
      this.facultySelectorVisible = true
    },
    handleFacultySelectedEvent (selectedFaculty) {
      this.facultySelectorVisible = false
      if (selectedFaculty && 'facultyId' in selectedFaculty && this.registerForm.facultyId !== selectedFaculty['facultyId']) {
        this.registerForm.facultyId = selectedFaculty['facultyId']
        this.registerForm.facultyName = selectedFaculty['facultyName']
      }
    },
    onBack () {
      this.$router.push({ name: 'Login', query: {type: 2}})
    }
  }
}
</script>

<style lang="scss">
@import "@/assets/styles/register";
</style>
