// angular_ngzorro/src/app/university/university-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {UniversityService} from '../../service/university.service';
import {SharedModule} from '../shared.module';
import {UniversityForm} from '../../types/req/UniversityForm';
import {MODAL_WIDTH} from '../../const'
import areas from '../../const/area.json';

@Component({
  selector: 'university-add',
  imports: [
    SharedModule
  ],
  templateUrl: './university-add.component.html',
  standalone: true
})
export class UniversityAddComponent implements OnInit {
  universityToSave:UniversityForm = {};
  universityForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增学校信息'
  modalWidth: string = MODAL_WIDTH
  provinceCityAreaOptions = areas.provinces;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private universityService: UniversityService
  ) {}

  ngOnInit(): void {
    this.universityForm = this.fb.group({
      name: ['', [Validators.required]],
      establishmentDate: [''],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      province: [''],
      city: [''],
      area: [''],
      provinceCityArea: [[]],
      location: ['', [Validators.required]],
      universityDescription: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.universityForm.controls) {
        this.universityForm.controls[i].markAsDirty();
        this.universityForm.controls[i].updateValueAndValidity();
      }
      if (!this.universityForm.valid) {
        this.saveLoading = false
        return
      }
      this.universityService.save(Object.assign(this.universityToSave, this.universityForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增学校信息'.slice()
    this.universityForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改学校信息'
      this.saveLoading = true
      this.universityService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.universityToSave = resp.data
            const provinceCityArea = []
            if (this.universityToSave.province) {
              provinceCityArea.push(this.universityToSave.province)
            }
            if (this.universityToSave.city) {
              provinceCityArea.push(this.universityToSave.city)
            }
            if (this.universityToSave.area) {
              provinceCityArea.push(this.universityToSave.area)
            }
            this.universityForm.patchValue(Object.assign({provinceCityArea: provinceCityArea},this.universityToSave));
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="universityForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>学校名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入学校名称'">
              <input nz-input formControlName="name" placeholder="请输入学校名称" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="establishmentDate">成立日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="establishmentDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入邮箱'">
              <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="area">省/市/区</nz-form-label>
            <nz-form-control>
              <nz-cascader [nzOptions]="provinceCityAreaOptions" formControlName="provinceCityArea"
                           nzValueProperty="code" nzLabelProperty="name"></nz-cascader>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="location" nzRequired>地址</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入地址'">
              <input nz-input formControlName="location" placeholder="请输入地址" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="universityDescription">学校简介</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="universityDescription" placeholder="请输入学校简介" maxlength="65535"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// v2_el/src/views/university/UniversityAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="universityForm" :label-width="formLabelWidth" ref="refUniversityForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="学校名称" prop="name">
            <el-input v-model="universityForm.name" placeholder="请输入学校名称" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="成立日期" prop="establishmentDate">
            <el-date-picker
                v-model="universityForm.establishmentDate" type="date" placeholder="成立日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="contactPhone">
            <el-input v-model="universityForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="邮箱" prop="email">
            <el-input v-model="universityForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="省/市/区">
            <el-cascader
                v-model="provinceCityArea"
                :options="provinceCityAreaOptions"
                :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"
                @change="handleChange"></el-cascader>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="地址" prop="location">
            <el-input v-model="universityForm.location" placeholder="请输入地址" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="22">
          <el-form-item label="学校简介" prop="universityDescription">
            <el-input v-model="universityForm.universityDescription" placeholder="请输入学校简介" type="textarea" :rows="5" maxlength="65535"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import universityApi from '@/api/universityApi'
import areas from '@/locales/area.json';
export default {
  name: 'UniversityAdd',
  components: {},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      universityForm: {
        name: '',
        establishmentDate: '',
        contactPhone: '',
        email: '',
        province: '',
        city: '',
        area: '',
        location: '',
        universityDescription: ''
      },
      rules: {
        name: [
          { required: true, message: '请输入学校名称', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        email: [
          { required: true, message: '请输入邮箱', trigger: 'blur' }
        ],
        location: [
          { required: true, message: '请输入地址', trigger: 'blur' }
        ],
      },
      provinceCityArea: [],
      provinceCityAreaOptions: areas.provinces
    }
  },
  created () {
    if (this.id) {
      universityApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.universityForm = resp.data
            this.provinceCityArea = []
            if (this.universityForm.province) {
              this.provinceCityArea.push(this.universityForm.province)
            }
            if (this.universityForm.city) {
              this.provinceCityArea.push(this.universityForm.city)
            }
            if (this.universityForm.area) {
              this.provinceCityArea.push(this.universityForm.area)
            }
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.universityForm = {
        name: '',
        establishmentDate: '',
        contactPhone: '',
        email: '',
        province: '',
        city: '',
        area: '',
        location: '',
        universityDescription: ''
      }
      this.provinceCityArea = []
      this.$emit('reset-university-add-event')
    },
    onSave () {
      this.$refs.refUniversityForm.validate((valid) => {
        if (valid) {
          universityApi.save(this.universityForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-university-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    handleChange(value) {
      if (value && value.length) {
        this.universityForm.province = value[0]
      }
      if (value && value.length > 1) {
        this.universityForm.city = value[1]
      }
      if (value && value.length > 2) {
        this.universityForm.area = value[1]
      }
    },
    onBack () {
      this.$emit('close-university-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
