// react_antd/src/pages/university/UniversitySelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Table, TableProps} from 'antd';
import type {University} from "@/types/resp/university";
import universityApi from '@/api/universityApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";


interface UniversitySelectorProps {
  visible: boolean;
  onUniversitySelected: (selectedUniversity: { universityId?: number; universityName?: string }) => void;
  onCloseUniversitySelector: () => void;
}

const UniversitySelector: React.FC<UniversitySelectorProps> = ({visible, onUniversitySelected, onCloseUniversitySelector}) => {

  const [universitySelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    universitySelectorForm.resetFields();
  };

  const [data, setData] = useState<University[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<University>> = await universityApi.find(universitySelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<University> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<University>['columns'] = [
    {title: '学校名称', dataIndex: 'name', key: 'name'},
    {title: '成立日期', key: 'establishmentDate', render: (_, record) => (
        <div>{record.establishmentDate.format('YYYY-MM-DD')}</div>
      )},
    {title: '联系电话', dataIndex: 'contactPhone', key: 'contactPhone'},
    {title: '邮箱', dataIndex: 'email', key: 'email'},
    {title: '省', dataIndex: 'provinceName', key: 'province'},
    {title: '市', dataIndex: 'cityName', key: 'city'},
    {title: '区', dataIndex: 'areaName', key: 'area'},
    {title: '地址', dataIndex: 'location', key: 'location'},
    {title: '学校简介', dataIndex: 'universityDescription', key: 'universityDescription', ellipsis: true}
  ];

// 行双击事件处理器
  const handleRowDoubleClick = (row: University) => {
    onUniversitySelected({
      universityId: row.id,
      universityName: row.name,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseUniversitySelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);

  return (
    <Modal title={"学校信息选择器(双击行选中)"} open={visible} onCancel={onCloseUniversitySelector} width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={universitySelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="学校名称">
          <Input maxLength={64} placeholder="请输入学校名称"/>
        </Form.Item>
        <Form.Item name="location" label="地址">
          <Input maxLength={255} placeholder="请输入地址"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<University> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
    </Modal>
  );
};

export default UniversitySelector;

// v2_el/src/views/university/UniversitySelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="searchParams">
        <el-form-item label="学校名称">
            <el-input v-model="searchParams.name" placeholder="请输入学校名称" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item label="地址">
            <el-input v-model="searchParams.location" placeholder="请输入地址" maxlength="255"></el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="pageData.list"
        border
        v-loading="pageData.loading"
        size="mini"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="universitySelected">
      <el-table-column prop="name" label="学校名称"></el-table-column>
      <el-table-column prop="establishmentDate" label="成立日期"></el-table-column>
      <el-table-column prop="contactPhone" label="联系电话"></el-table-column>
      <el-table-column prop="email" label="邮箱"></el-table-column>
      <el-table-column prop="provinceName" label="省"></el-table-column>
      <el-table-column prop="cityName" label="市"></el-table-column>
      <el-table-column prop="areaName" label="区"></el-table-column>
      <el-table-column prop="location" label="地址"></el-table-column>
        <el-table-column label="学校简介">
          <template v-slot="{ row }">
            <div class="ellipsis">
              {{ row.universityDescription }}
            </div>
          </template>
        </el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="paginationChange"
          :current-page="pageData.current"
          :page-sizes="pageData.pageSizes"
          :page-size="pageData.size"
          background
          layout="total, prev, pager, next, jumper"
          :total="pageData.count">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import universityApi from '@/api/universityApi'
import listQueryMixin from '@/mixins/listQueryMixin'
export default {
  name: 'UniversitySelector',
  components: {},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        name: '',
        location: ''
      },
    }
  },
  methods: {
    getPageData (p) {
      return universityApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        name: '',
        location: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    universitySelected (row) {
      this.$emit('university-selected-event', {
        universityId: row.id,
        universityName: row.name,
      })
    },
    onBack () {
      this.$emit('university-selected-event')
    }
  }
}
</script>

<style lang="scss">
</style>
