// v2_el/src/views/faculty/FacultyAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="facultyForm" :label-width="formLabelWidth" ref="refFacultyForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="学校名称" prop="universityName">
            <el-input v-model="facultyForm.universityName" placeholder="请选择学校名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findUniversity"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="院系名称" prop="name">
            <el-input v-model="facultyForm.name" placeholder="请输入院系名称" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="成立日期" prop="establishmentDate">
            <el-date-picker
                v-model="facultyForm.establishmentDate" type="date" placeholder="成立日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="contactPhone">
            <el-input v-model="facultyForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="邮箱" prop="email">
            <el-input v-model="facultyForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="办公地点" prop="officeLocation">
            <el-input v-model="facultyForm.officeLocation" placeholder="请输入办公地点" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="院系网址" prop="website">
            <el-input v-model="facultyForm.website" placeholder="请输入院系网址" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="22">
          <el-form-item label="院系简介" prop="facultyDescription">
            <el-input v-model="facultyForm.facultyDescription" placeholder="请输入院系简介" type="textarea" :rows="5" maxlength="65535"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="universitySelectorVisible" v-if="universitySelectorVisible" title="学校信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <university-selector @university-selected-event="handleUniversitySelectedEvent">
      </university-selector>
    </el-dialog>
  </div>
</template>

<script>
import facultyApi from '@/api/facultyApi'
import UniversitySelector from "@/views/university/UniversitySelector.vue";
export default {
  name: 'FacultyAdd',
  components: {UniversitySelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      facultyForm: {
        universityId: '',
        universityName: '',
        name: '',
        establishmentDate: '',
        contactPhone: '',
        email: '',
        officeLocation: '',
        website: '',
        facultyDescription: ''
      },
      rules: {
        universityName: [
          { required: true, message: '请输入学校名称', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '请输入院系名称', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        email: [
          { required: true, message: '请输入邮箱', trigger: 'blur' }
        ],
        officeLocation: [
          { required: true, message: '请输入办公地点', trigger: 'blur' }
        ],
      },
      universitySelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      facultyApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.facultyForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.facultyForm = {
        universityId: '',
        universityName: '',
        name: '',
        establishmentDate: '',
        contactPhone: '',
        email: '',
        officeLocation: '',
        website: '',
        facultyDescription: ''
      }
      this.$emit('reset-faculty-add-event')
    },
    onSave () {
      this.$refs.refFacultyForm.validate((valid) => {
        if (valid) {
          facultyApi.save(this.facultyForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-faculty-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findUniversity () {
      this.universitySelectorVisible = true
    },
    handleUniversitySelectedEvent (selectedUniversity) {
      this.universitySelectorVisible = false
      if (selectedUniversity && 'universityId' in selectedUniversity && this.facultyForm.universityId !== selectedUniversity['universityId']) {
        this.facultyForm.universityId = selectedUniversity['universityId']
        this.facultyForm.universityName = selectedUniversity['universityName']
      }
    },
    onBack () {
      this.$emit('close-faculty-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/faculty/faculty-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {FacultyService} from '../../service/faculty.service';
import {SharedModule} from '../shared.module';
import {FacultyForm} from '../../types/req/FacultyForm';
import {MODAL_WIDTH} from '../../const'
import {UniversitySelectorComponent} from '../university/university-selector.component';

@Component({
  selector: 'faculty-add',
  imports: [
    UniversitySelectorComponent,
    SharedModule
  ],
  templateUrl: './faculty-add.component.html',
  standalone: true
})
export class FacultyAddComponent implements OnInit {
  facultyToSave:FacultyForm = {};
  facultyForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增院系信息'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(UniversitySelectorComponent, { static: false }) universitySelectorComponent!: UniversitySelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private facultyService: FacultyService
  ) {}

  ngOnInit(): void {
    this.facultyForm = this.fb.group({
      universityId: [0],
      universityName: ['', [Validators.required]],
      name: ['', [Validators.required]],
      establishmentDate: [''],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      officeLocation: ['', [Validators.required]],
      website: [''],
      facultyDescription: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.facultyForm.controls) {
        this.facultyForm.controls[i].markAsDirty();
        this.facultyForm.controls[i].updateValueAndValidity();
      }
      if (!this.facultyForm.valid) {
        this.saveLoading = false
        return
      }
      this.facultyService.save(Object.assign(this.facultyToSave, this.facultyForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增院系信息'.slice()
    this.facultyForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改院系信息'
      this.saveLoading = true
      this.facultyService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.facultyToSave = resp.data
            this.facultyForm.patchValue(this.facultyToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findUniversity() {
    this.universitySelectorComponent.display()
  }

  handleUniversitySelectedEvent(selectedUniversity: { universityId?: number; universityName?: string; }) {
    if (selectedUniversity && 'universityId' in selectedUniversity) {
      this.facultyForm.patchValue(selectedUniversity);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="facultyForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="universityName" nzRequired>学校名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择学校名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="universityNameSuffixIconButton">
                <input nz-input formControlName="universityName" placeholder="请选择学校名称" readonly />
              </nz-input-group>
              <ng-template #universityNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findUniversity()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>院系名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入院系名称'">
              <input nz-input formControlName="name" placeholder="请输入院系名称" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="establishmentDate">成立日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="establishmentDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入邮箱'">
              <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="officeLocation" nzRequired>办公地点</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入办公地点'">
              <input nz-input formControlName="officeLocation" placeholder="请输入办公地点" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="website">院系网址</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="website" placeholder="请输入院系网址" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="facultyDescription">院系简介</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="facultyDescription" placeholder="请输入院系简介" maxlength="65535"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<university-selector (universitySelectedEvent)="handleUniversitySelectedEvent($event)"></university-selector>
