// v2_el/src/views/student/StudentSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="searchParams">
        <el-form-item label="学号">
            <el-input v-model="searchParams.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
        </el-form-item>
        <el-form-item label="性别" prop="gender">
          <el-select v-model="searchParams.gender" placeholder="请选择性别">
            <el-option label="男" :value="1"></el-option>
            <el-option label="女" :value="2"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="专业名称" prop="majorName">
          <el-input v-model="searchParams.majorName" placeholder="请选择专业名称" readonly="readonly">
            <i slot="suffix" class="el-input__icon el-icon-search" @click="findMajor"></i>
          </el-input>
        </el-form-item>
        <el-form-item label="年级" prop="grade">
          <el-input-number v-model="searchParams.grade" :min="2000" :max="2100"></el-input-number>
        </el-form-item>
        <el-form-item label="联系电话">
            <el-input v-model="searchParams.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="pageData.list"
        border
        v-loading="pageData.loading"
        size="mini"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="studentSelected">
      <el-table-column prop="studentNumber" label="学号"></el-table-column>
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="password" label="密码"></el-table-column>
      <el-table-column prop="gender" label="性别">
        <template v-slot="{ row }">
          <div v-if="row.gender === 1">男</div>
          <div v-if="row.gender === 2">女</div>
        </template>
      </el-table-column>
      <el-table-column prop="birthDate" label="出生日期"></el-table-column>
      <el-table-column prop="majorId" label="专业id"></el-table-column>
      <el-table-column prop="grade" label="年级"></el-table-column>
      <el-table-column prop="contactPhone" label="联系电话"></el-table-column>
      <el-table-column prop="email" label="邮箱"></el-table-column>
      <el-table-column prop="provinceName" label="省"></el-table-column>
      <el-table-column prop="cityName" label="市"></el-table-column>
      <el-table-column prop="areaName" label="区"></el-table-column>
      <el-table-column prop="address" label="家庭地址"></el-table-column>
      <el-table-column prop="enrollmentDate" label="入学日期"></el-table-column>
      <el-table-column prop="graduationDate" label="毕业日期"></el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="paginationChange"
          :current-page="pageData.current"
          :page-sizes="pageData.pageSizes"
          :page-size="pageData.size"
          background
          layout="total, prev, pager, next, jumper"
          :total="pageData.count">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script>
import studentApi from '@/api/studentApi'
import MajorSelector from "@/views/major/MajorSelector.vue";
import listQueryMixin from '@/mixins/listQueryMixin'

export default {
  name: 'StudentSelector',
  components: {MajorSelector,},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        studentNumber: '',
        gender: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: ''
      },
      majorSelectorVisible: false
    }
  },
  methods: {
    getPageData (p) {
      return studentApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        studentNumber: '',
        gender: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    studentSelected (row) {
      this.$emit('student-selected-event', {
        studentId: row.id,
        studentNumber: row.studentNumber,
      })
    },
    findMajor () {
      this.majorSelectorVisible = true
    },
    handleMajorSelectedEvent (selectedMajor) {
      this.majorSelectorVisible = false
      if (selectedMajor && 'majorId' in selectedMajor && this.searchParams.majorId !== selectedMajor['majorId']) {
        this.searchParams.majorId = selectedMajor['majorId']
        this.searchParams.majorName = selectedMajor['majorName']
      }
    },
    onBack () {
      this.$emit('student-selected-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/student/StudentSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, InputNumber, Modal, Select, Table, TableProps} from 'antd';
import type {Student} from "@/types/resp/student";
import studentApi from '@/api/studentApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import MajorSelector from "@/pages/major/MajorSelector.tsx";


interface StudentSelectorProps {
  visible: boolean;
  onStudentSelected: (selectedStudent: { studentId?: number;studentNumber?: string; }) => void;
  onCloseStudentSelector: () => void;
}

const StudentSelector: React.FC<StudentSelectorProps> = ({visible, onStudentSelected, onCloseStudentSelector}) => {

  const [studentSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    studentSelectorForm.resetFields();
  };

  const [data, setData] = useState<Student[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Student>> = await studentApi.find(studentSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Student> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Student>['columns'] = [
    {title: '学号', dataIndex: 'studentNumber', key: 'studentNumber', width: 60},
    {title: '姓名', dataIndex: 'name', key: 'name', width: 60},
    {title: '密码', dataIndex: 'password', key: 'password', width: 60},
    {title: '性别', key: 'gender', width: 40, render: (_, record) => (
        <span>
        {(function () {
          if (record.gender === 1) return '男';
          else if (record.gender === 2) return '女';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '出生日期', key: 'birthDate', width: 90, render: (_, record) => (
        <div>{record.birthDate.format('YYYY-MM-DD')}</div>
      )},
    {title: '专业名称', dataIndex: 'majorName', key: 'majorName', width: 120},
    {title: '年级', dataIndex: 'grade', key: 'grade', width: 50},
    {title: '联系电话', dataIndex: 'contactPhone', key: 'contactPhone', width: 120},
    {title: '邮箱', dataIndex: 'email', key: 'email', width: 120},
    {title: '省', dataIndex: 'provinceName', key: 'province', width: 100},
    {title: '市', dataIndex: 'cityName', key: 'city', width: 100},
    {title: '区', dataIndex: 'areaName', key: 'area', width: 100},
    {title: '家庭地址', dataIndex: 'address', key: 'address', width: 140},
    {title: '入学日期', key: 'enrollmentDate', width: 90, render: (_, record) => (
      <div>{record.enrollmentDate.format('YYYY-MM-DD')}</div>
    )},
    {title: '毕业日期', key: 'graduationDate', width: 90, render: (_, record) => (
      <div>{record.graduationDate.format('YYYY-MM-DD')}</div>
    )},
  ];

  const handleRowDoubleClick = (row: Student) => {
    onStudentSelected({
      studentId: row.id,
      studentNumber: row.studentNumber,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseStudentSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);

  const [majorSelectorVisible, setMajorSelectorVisible] = useState(false);
  const findMajor = () => {
    setMajorSelectorVisible(true);
  }
  const handleMajorSelected = (selectedMajor: { majorId?: number; majorName?: string; }) => {
    setMajorSelectorVisible(false)
    if (selectedMajor && 'majorId' in selectedMajor) {
      studentSelectorForm.setFieldsValue(Object.assign(studentSelectorForm.getFieldsValue(), {
      majorId: selectedMajor['majorId'],
      majorName: selectedMajor['majorName'],
      }));
    }
  };
  const handleCloseMajorSelector = () => {
    setMajorSelectorVisible(false)
  };

  return (
    <Modal title={"学生信息选择器(双击行选中)"} open={visible} onCancel={onCloseStudentSelector} width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={studentSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="studentNumber" label="学号">
          <Input maxLength={20} placeholder="请输入学号"/>
        </Form.Item>
        <Form.Item name="gender" label="性别">
          <Select placeholder="请选择性别" options={[
            { value: 1, label: <span>男</span> },
            { value: 2, label: <span>女</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item name="majorName" label="专业名称">
          <Input.Search placeholder="请选择专业名称" onSearch={findMajor} readOnly={true} />
        </Form.Item>
        <Form.Item name="grade" label="年级">
          <InputNumber min={2000} max={2100} />
        </Form.Item>
        <Form.Item name="contactPhone" label="联系电话">
          <Input maxLength={64} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<Student> columns={columns} dataSource={data} size="small"
                      scroll={{ x: 'max-content' }}
                      rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
      <MajorSelector visible={majorSelectorVisible} onMajorSelected={handleMajorSelected} onCloseMajorSelector={handleCloseMajorSelector} />
    </Modal>
  );
};

export default StudentSelector;
