// v2_el/src/views/course/CourseAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="courseForm" :label-width="formLabelWidth" ref="refCourseForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="院系名称" prop="facultyName">
            <el-input v-model="courseForm.facultyName" placeholder="请选择院系名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findFaculty"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="教师姓名" prop="teacherName">
            <el-input v-model="courseForm.teacherName" placeholder="请选择教师姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findTeacher"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="课程代码" prop="code">
            <el-input v-model="courseForm.code" placeholder="请输入课程代码" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="课程名称" prop="name">
            <el-input v-model="courseForm.name" placeholder="请输入课程名称" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="学分" prop="credit">
            <el-input-number v-model="courseForm.credit" :min="1" :max="10"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="22">
          <el-form-item label="课程描述" prop="courseDescription">
            <el-input v-model="courseForm.courseDescription" placeholder="请输入课程描述" type="textarea" :rows="5" maxlength="65535"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="facultySelectorVisible" v-if="facultySelectorVisible" title="院系信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <faculty-selector @faculty-selected-event="handleFacultySelectedEvent">
      </faculty-selector>
    </el-dialog>
    <el-dialog :visible.sync="teacherSelectorVisible" v-if="teacherSelectorVisible" title="教师信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <teacher-selector @teacher-selected-event="handleTeacherSelectedEvent">
      </teacher-selector>
    </el-dialog>
  </div>
</template>

<script>
import courseApi from '@/api/courseApi'
import FacultySelector from "@/views/faculty/FacultySelector.vue";
import TeacherSelector from "@/views/teacher/TeacherSelector.vue";
export default {
  name: 'CourseAdd',
  components: {FacultySelector,TeacherSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      courseForm: {
        facultyId: '',
        facultyName: '',
        teacherId: '',
        teacherName: '',
        code: '',
        name: '',
        credit: '',
        courseDescription: ''
      },
      rules: {
        facultyName: [
          { required: true, message: '请输入院系名称', trigger: 'blur' }
        ],
        teacherName: [
          { required: true, message: '请输入教师姓名', trigger: 'blur' }
        ],
        code: [
          { required: true, message: '请输入课程代码', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '请输入课程名称', trigger: 'blur' }
        ],
        credit: [
          { required: true, message: '请输入学分', trigger: 'blur' }
        ],
      },
      facultySelectorVisible: false,
      teacherSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      courseApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.courseForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.courseForm = {
        facultyId: '',
        facultyName: '',
        teacherId: '',
        teacherName: '',
        code: '',
        name: '',
        credit: '',
        courseDescription: ''
      }
      this.$emit('reset-course-add-event')
    },
    onSave () {
      this.$refs.refCourseForm.validate((valid) => {
        if (valid) {
          courseApi.save(this.courseForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-course-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findFaculty () {
      this.facultySelectorVisible = true
    },
    handleFacultySelectedEvent (selectedFaculty) {
      this.facultySelectorVisible = false
      if (selectedFaculty && 'facultyId' in selectedFaculty && this.courseForm.facultyId !== selectedFaculty['facultyId']) {
        this.courseForm.facultyId = selectedFaculty['facultyId']
        this.courseForm.facultyName = selectedFaculty['facultyName']
      }
    },
    findTeacher () {
      this.teacherSelectorVisible = true
    },
    handleTeacherSelectedEvent (selectedTeacher) {
      this.teacherSelectorVisible = false
      if (selectedTeacher && 'teacherId' in selectedTeacher && this.courseForm.teacherId !== selectedTeacher['teacherId']) {
        this.courseForm.teacherId = selectedTeacher['teacherId']
        this.courseForm.teacherName = selectedTeacher['teacherName']
      }
    },
    onBack () {
      this.$emit('close-course-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/course/course-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {CourseService} from '../../service/course.service';
import {SharedModule} from '../shared.module';
import {CourseForm} from '../../types/req/CourseForm';
import {MODAL_WIDTH} from '../../const'
import {FacultySelectorComponent} from '../faculty/faculty-selector.component';
import {TeacherSelectorComponent} from '../teacher/teacher-selector.component';

@Component({
  selector: 'course-add',
  imports: [
    FacultySelectorComponent,
    TeacherSelectorComponent,
    SharedModule
  ],
  templateUrl: './course-add.component.html',
  standalone: true
})
export class CourseAddComponent implements OnInit {
  courseToSave:CourseForm = {};
  courseForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增课程信息'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(FacultySelectorComponent, { static: false }) facultySelectorComponent!: FacultySelectorComponent;
  @ViewChild(TeacherSelectorComponent, { static: false }) teacherSelectorComponent!: TeacherSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private courseService: CourseService
  ) {}

  ngOnInit(): void {
    this.courseForm = this.fb.group({
      facultyId: [0],
      facultyName: ['', [Validators.required]],
      teacherId: [0],
      teacherName: ['', [Validators.required]],
      code: ['', [Validators.required]],
      name: ['', [Validators.required]],
      credit: [0, [Validators.required]],
      courseDescription: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.courseForm.controls) {
        this.courseForm.controls[i].markAsDirty();
        this.courseForm.controls[i].updateValueAndValidity();
      }
      if (!this.courseForm.valid) {
        this.saveLoading = false
        return
      }
      this.courseService.save(Object.assign(this.courseToSave, this.courseForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增课程信息'.slice()
    this.courseForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改课程信息'
      this.saveLoading = true
      this.courseService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.courseToSave = resp.data
            this.courseForm.patchValue(this.courseToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findFaculty() {
    this.facultySelectorComponent.display()
  }

  handleFacultySelectedEvent(selectedFaculty: { facultyId?: number; facultyName?: string; }) {
    if (selectedFaculty && 'facultyId' in selectedFaculty) {
      this.courseForm.patchValue(selectedFaculty);
    }
  }

  findTeacher() {
    this.teacherSelectorComponent.display()
  }

  handleTeacherSelectedEvent(selectedTeacher: { teacherId?: number; teacherName?: string; }) {
    if (selectedTeacher && 'teacherId' in selectedTeacher) {
      this.courseForm.patchValue(selectedTeacher);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="courseForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="facultyName" nzRequired>院系名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择院系名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="facultyNameSuffixIconButton">
                <input nz-input formControlName="facultyName" placeholder="请选择院系名称" readonly />
              </nz-input-group>
              <ng-template #facultyNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findFaculty()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="teacherName" nzRequired>教师姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择教师姓名'">
              <nz-input-group nzSearch [nzAddOnAfter]="teacherNameSuffixIconButton">
                <input nz-input formControlName="teacherName" placeholder="请选择教师姓名" readonly />
              </nz-input-group>
              <ng-template #teacherNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findTeacher()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="code" nzRequired>课程代码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入课程代码'">
              <input nz-input formControlName="code" placeholder="请输入课程代码" maxlength="32"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>课程名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入课程名称'">
              <input nz-input formControlName="name" placeholder="请输入课程名称" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="credit" nzRequired>学分</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入学分'">
            <nz-input-number formControlName="credit" [nzMin]="1" [nzMax]="10" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="courseDescription">课程描述</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="courseDescription" placeholder="请输入课程描述" maxlength="65535"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<faculty-selector (facultySelectedEvent)="handleFacultySelectedEvent($event)"></faculty-selector>
<teacher-selector (teacherSelectedEvent)="handleTeacherSelectedEvent($event)"></teacher-selector>
