// v3_el/src/views/course/CourseList.vue
<template>
  <div class="course-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>课程信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="courseQueryForm" ref="courseQueryFormRef" :rules="rules">
      <el-form-item label="院系名称" prop="facultyName">
        <el-input v-model="courseQueryForm.facultyName" placeholder="请选择院系名称" readonly="readonly">
          <template #suffix>
            <el-icon @click="findFaculty"><Search/></el-icon>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item label="教师姓名" prop="teacherName">
        <el-input v-model="courseQueryForm.teacherName" placeholder="请选择教师姓名" readonly="readonly">
          <template #suffix>
            <el-icon @click="findTeacher"><Search/></el-icon>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item label="课程名称" prop="name">
        <el-input v-model="courseQueryForm.name" placeholder="请输入课程名称" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="facultyName" label="院系名称"></el-table-column>
      <el-table-column prop="teacherName" label="教师姓名"></el-table-column>
      <el-table-column prop="code" label="课程代码"></el-table-column>
      <el-table-column prop="name" label="课程名称"></el-table-column>
      <el-table-column prop="credit" label="学分"></el-table-column>
      <el-table-column label="课程描述">
        <template v-slot="{ row }">
          <div class="ellipsis">
            {{ row.courseDescription }}
          </div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="facultySelectorVisible" v-if="facultySelectorVisible" title="院系信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <faculty-selector @faculty-selected-event="handleFacultySelectedEvent">
      </faculty-selector>
    </el-dialog>
    <el-dialog v-model="teacherSelectorVisible" v-if="teacherSelectorVisible" title="教师信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <teacher-selector @teacher-selected-event="handleTeacherSelectedEvent">
      </teacher-selector>
    </el-dialog>
    <el-dialog v-model="courseAddVisible" v-if="courseAddVisible" :title="courseAddTitle" :top="dialogTop" :width="dialogWidth">
      <course-add :id="selectedCourseId" @close-course-add-event="handleCloseCourseAddEvent" @reset-course-add-event="handleResetCourseAddEvent">
      </course-add>
    </el-dialog>
    <el-dialog v-model="courseViewVisible" v-if="courseViewVisible" title="课程信息详情" :top="dialogTop" :width="dialogWidth">
      <course-view :id="selectedCourseId" @close-course-view-event="handleCloseCourseViewEvent">
      </course-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {inject, onMounted, reactive, ref, toRefs} from 'vue';
import courseApi from '@/api/courseApi'
import type {CourseQueryForm} from "@/types/req/courseQueryForm";
import type {Course} from "@/types/resp/course";
import {ElMessage, ElMessageBox, type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";
import {Search} from '@element-plus/icons-vue';
import FacultySelector from "@/views/faculty/FacultySelector.vue";
import TeacherSelector from "@/views/teacher/TeacherSelector.vue";
import CourseAdd from "@/views/course/CourseAdd.vue"
import CourseView from "@/views/course/CourseView.vue"
import {exportToExcel} from "@/composables/exportUtil.ts";

const courseQueryFormRef = ref<FormInstance | null>(null);
let courseQueryForm = reactive<CourseQueryForm>({
  facultyId: 0,
  facultyName: '',
  teacherId: 0,
  teacherName: '',
  name: '',
})

const state = reactive({
  loading: false,
  tableData: [] as Course[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedCourseId = ref<number>(0)
const facultySelectorVisible = ref<boolean>(false)
const teacherSelectorVisible = ref<boolean>(false)
const courseAddVisible = ref<boolean>(false)
const courseViewVisible = ref<boolean>(false)
const courseAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<Course>> = await courseApi.find(courseQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<Course> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (courseQueryFormRef.value) {
    courseQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedCourseId.value = 0
  courseAddVisible.value = true
  courseAddTitle.value = '课程信息新增'
}
const editRow = (id: number) => {
  selectedCourseId.value = id
  courseAddVisible.value = true
  courseAddTitle.value = '课程信息编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    courseApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedCourseId.value = id
  courseViewVisible.value = true
}

const findFaculty = () => {
  facultySelectorVisible.value = true
}

const handleFacultySelectedEvent = (selectedFaculty: any) => {
  facultySelectorVisible.value = false
  if (selectedFaculty && 'facultyId' in selectedFaculty && courseQueryForm.facultyId !== selectedFaculty['facultyId']) {
    courseQueryForm.facultyId = selectedFaculty['facultyId']
    courseQueryForm.facultyName = selectedFaculty['facultyName']
  }
}
const findTeacher = () => {
  teacherSelectorVisible.value = true
}

const handleTeacherSelectedEvent = (selectedTeacher: any) => {
  teacherSelectorVisible.value = false
  if (selectedTeacher && 'teacherId' in selectedTeacher && courseQueryForm.teacherId !== selectedTeacher['teacherId']) {
    courseQueryForm.teacherId = selectedTeacher['teacherId']
    courseQueryForm.teacherName = selectedTeacher['teacherName']
  }
}

const handleCloseCourseViewEvent = () => {
  courseViewVisible.value = false
}

const handleResetCourseAddEvent = () => {
  courseAddTitle.value = '课程信息新增'
}

const handleCloseCourseAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  courseAddVisible.value = false
}

const onExport = () => {
  const headers = ['院系名称', '教师姓名', '课程代码', '课程名称', '学分', '课程描述']
  courseApi.find(courseQueryForm).then(data => {
    if (!data || !data.data || data.data.list.length < 1) {
      ElMessage.error('无数据导出')
      return
    }
    const exportData = []
    for (const d of data.data.list) {
      exportData.push([d.facultyName, d.teacherName, d.code, d.name, d.credit, d.courseDescription])
    }
    exportToExcel(headers, exportData)
  })
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/course/course-list.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {CourseService} from '../../service/course.service';
import {CourseQueryForm} from '../../types/req/CourseQueryForm';
import {SharedModule} from '../shared.module';
import {Course} from '../../types/resp/Course';
import {Page} from '../../types/page';
import {CourseAddComponent} from './course-add.component';
import {CourseViewComponent} from './course-view.component';
import {NzModalService} from 'ng-zorro-antd/modal';
import {FacultySelectorComponent} from '../faculty/faculty-selector.component';
import {TeacherSelectorComponent} from '../teacher/teacher-selector.component';
import {AttendanceQueryForm} from '../../types/req/AttendanceQueryForm';
import {getAttendanceStatusText} from '../../util/dictTranslator';
import {exportToExcel} from '../../util/exportUtil';

@Component({
  selector: 'course-list',
  imports: [
    FacultySelectorComponent,
    TeacherSelectorComponent,
    CourseAddComponent,
    CourseViewComponent,
    SharedModule
  ],
  templateUrl: './course-list.component.html',
  standalone: true
})
export class CourseListComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: Course[] = [];
  total: number = 0

  @ViewChild(FacultySelectorComponent, { static: false }) facultySelectorComponent!: FacultySelectorComponent;
  @ViewChild(TeacherSelectorComponent, { static: false }) teacherSelectorComponent!: TeacherSelectorComponent;
  @ViewChild(CourseAddComponent, { static: false }) courseAddComponent!: CourseAddComponent;
  @ViewChild(CourseViewComponent, { static: false }) courseViewComponent!: CourseViewComponent;

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private courseService: CourseService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      facultyId: [0],
      facultyName: [''],
      teacherId: [0],
      teacherName: [''],
      name: [''],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.courseService.find(new CourseQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<Course> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onAdd() {
    this.courseAddComponent.display(0)
  }

  onExport() {
    try {
      const headers = ['院系名称', '教师姓名', '课程代码', '课程名称', '学分', '课程描述']
      this.searchLoading = true
      this.courseService.find(new CourseQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1 || !resp.data || resp.data.list.length < 1) {
            this.message.error('无数据导出')
            return
          }
          const exportData = []
          for (const d of resp.data.list) {
            exportData.push([d.facultyName, d.teacherName, d.code, d.name, d.credit, d.courseDescription])
          }
          exportToExcel(headers, exportData)
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  editRow(id: number) {
    this.courseAddComponent.display(id)
  }

  delRow(id: number) {
    this.modal.confirm({
      nzTitle: '<i>删除提示</i>',
      nzContent: '<b>确定要删除吗?</b>',
      nzOnOk: () => {
        this.courseService.del(id).subscribe({
          next: (resp) => {
            if (resp && resp.code === 1) {
              this.message.success('删除成功!')
              this.onSearch()
            } else {
              this.message.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          },
          complete: () => {
            this.searchLoading = false
          }
        })
      }
    });
  }

  detailRow(record: Course) {
    this.courseViewComponent.display(record)
  }

  findFaculty() {
    this.facultySelectorComponent.display()
  }

  handleFacultySelectedEvent(selectedFaculty: { facultyId?: number; facultyName?: string; }) {
    if (selectedFaculty && 'facultyId' in selectedFaculty) {
      this.searchForm.patchValue(selectedFaculty);
    }
  }

  findTeacher() {
    this.teacherSelectorComponent.display()
  }

  handleTeacherSelectedEvent(selectedTeacher: { teacherId?: number; teacherName?: string; }) {
    if (selectedTeacher && 'teacherId' in selectedTeacher) {
      this.searchForm.patchValue(selectedTeacher);
    }
  }

  onAdded(addedFlag: boolean) {
    if (addedFlag) {
      this.onSearch()
    }
  }
}

<nz-breadcrumb class="breadcrumb">
  <nz-breadcrumb-item>
    <a routerLink="/Home">主页</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>课程信息列表</nz-breadcrumb-item>
</nz-breadcrumb>
<form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
  <nz-form-item>
    <nz-form-label nzFor="facultyName">院系名称</nz-form-label>
    <nz-form-control>
      <nz-input-group nzSearch [nzAddOnAfter]="facultyNameSuffixIconButton">
        <input nz-input formControlName="facultyName" placeholder="请选择院系名称" readonly />
      </nz-input-group>
      <ng-template #facultyNameSuffixIconButton>
        <button nz-button nzType="primary" nzSearch (click)="findFaculty()"><nz-icon nzType="search" /></button>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="teacherName">教师姓名</nz-form-label>
    <nz-form-control>
      <nz-input-group nzSearch [nzAddOnAfter]="teacherNameSuffixIconButton">
        <input nz-input formControlName="teacherName" placeholder="请选择教师姓名" readonly />
      </nz-input-group>
      <ng-template #teacherNameSuffixIconButton>
        <button nz-button nzType="primary" nzSearch (click)="findTeacher()"><nz-icon nzType="search" /></button>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="name">课程名称</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="name" placeholder="请输入课程名称" />
    </nz-form-control>
  </nz-form-item>
  <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
  <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
  <button nz-button type="button" class="margin-button" nzType="primary" (click)="onAdd()">新增</button>
  <button nz-button type="button" class="margin-button" nzType="primary" [nzLoading]="searchLoading" (click)="onExport()">导出</button>
</form>
<nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
  <thead>
    <tr>
      <th>院系名称</th>
      <th>教师姓名</th>
      <th>课程代码</th>
      <th>课程名称</th>
      <th>学分</th>
      <th>课程描述</th>
      <th nzWidth="250px">操作</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let data of basicTable.data">
      <td>{{data.facultyName}}</td>
      <td>{{data.teacherName}}</td>
      <td>{{data.code}}</td>
      <td>{{data.name}}</td>
      <td>{{data.credit}}</td>
      <td class="ellipsis">{{data.courseDescription}}</td>
      <td>
        <button nz-button type="button" nzType="primary" (click)="editRow(data.id)">编辑</button>
        <button nz-button type="button" nzDanger class="margin-button" (click)="delRow(data.id)">删除</button>
        <button nz-button type="button" class="margin-button" (click)="detailRow(data)">详情</button>
      </td>
    </tr>
  </tbody>
</nz-table>
<faculty-selector (facultySelectedEvent)="handleFacultySelectedEvent($event)"></faculty-selector>
<teacher-selector (teacherSelectedEvent)="handleTeacherSelectedEvent($event)"></teacher-selector>
<course-add (addedEvent)="onAdded($event)"></course-add>
<course-view></course-view>
