// v3_el/src/views/StudentRegister.vue
<template>
  <div class="register-page">
    <div class="register">
      <div class="login-title">{{ $t('title') }}</div>
      <div class="login-subtitle">{{ $t('studentRegisterTitle') }}</div>
      <el-form :model="studentRegisterForm" :rules="rules" ref="studentRegisterFormRef" @keyup.enter.native="onRegister" label-width="80px">
        <el-row>
          <el-col :span="8">
            <el-form-item label="学号" prop="studentNumber">
              <el-input v-model="studentRegisterForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="studentRegisterForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="性别" prop="gender">
              <el-select v-model="studentRegisterForm.gender" placeholder="请选择性别">
                <el-option label="男" :value="1"></el-option>
                <el-option label="女" :value="2"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="密码" prop="password">
              <el-input v-model="studentRegisterForm.password" type="password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item prop="password2" label="确认密码">
              <el-input v-model="studentRegisterForm.password2" type="password" placeholder="请确认确认密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="出生日期" prop="birthDate">
              <el-date-picker
                  v-model="studentRegisterForm.birthDate" type="date" placeholder="出生日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="专业名称" prop="majorName">
              <el-input v-model="studentRegisterForm.majorName" placeholder="请选择专业名称" readonly="readonly">
                <template #suffix>
                  <el-icon @click="findMajor"><Search/></el-icon>
                </template>
              </el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="年级" prop="grade">
              <el-input-number v-model="studentRegisterForm.grade" :min="2000" :max="2100"></el-input-number>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="入学日期" prop="enrollmentDate">
              <el-date-picker
                  v-model="studentRegisterForm.enrollmentDate" type="date" placeholder="入学日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="联系电话" prop="contactPhone">
              <el-input v-model="studentRegisterForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="studentRegisterForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="毕业日期" prop="graduationDate">
              <el-date-picker
                  v-model="studentRegisterForm.graduationDate" type="date" placeholder="毕业日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="省/市/区">
              <el-cascader
                v-model="provinceCityArea"
                :options="provinceCityAreaOptions"
                :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"
                @change="handleChange"/>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item prop="verificationCode" label="验证码">
              <el-input v-model="studentRegisterForm.verificationCode" placeholder="请输入验证码"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item>
              <canvas id="captchaCanvas" width="150" height="50" @click="drawCaptcha"></canvas>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="家庭地址" prop="address">
              <el-input v-model="studentRegisterForm.address" placeholder="请输入家庭地址" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <div class="center-container">
              <el-button type="primary" @click="onRegister" :loading="loading">注册</el-button>
              <el-button @click="onReset">重置</el-button>
              <el-button type="primary" @click="onBack">返回登录</el-button>
            </div>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <el-dialog v-model="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {inject, onMounted, reactive, ref, toRefs} from 'vue';
import {useCaptcha} from '@/composables/useCaptcha'
import studentApi from '@/api/studentApi'
import MajorSelector from "@/views/major/MajorSelector.vue";
import {ElMessage, type FormInstance} from "element-plus";
import type {StudentRegisterForm} from "@/types/req/studentRegisterForm";
import areas from "@/locales/area.json";
import type {Result} from "@/types/result";
import {useRouter} from "vue-router";
import {Search} from "@element-plus/icons-vue";

const { generatedVerificationCode, drawCaptcha } = useCaptcha()

const studentRegisterFormRef = ref<FormInstance | null>(null);
let studentRegisterForm = reactive<StudentRegisterForm>({
  studentNumber: '',
  name: '',
  password: '',
  password2: '',
  gender: 1,
  birthDate: '',
  majorId: 0,
  majorName: '',
  grade: 0,
  contactPhone: '',
  email: '',
  province: '',
  city: '',
  area: '',
  address: '',
  enrollmentDate: '',
  graduationDate: '',
  verificationCode: ''
})
const provinceCityArea = ref<string[]>([])
const provinceCityAreaOptions = areas.provinces
const majorSelectorVisible = ref<boolean>(false)
const loading = ref<boolean>(false)

const rules = reactive({
  studentNumber: [
    { required: true, message: '请输入学号', trigger: 'blur' }
  ],
  name: [
    { required: true, message: '请输入姓名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' }
  ],
  password2: [
    { required: true, message: '请确认密码', trigger: 'blur' }
  ],
  gender: [
    { required: true, message: '请输入性别', trigger: 'blur' }
  ],
  birthDate: [
    { required: true, message: '请输入出生日期', trigger: 'blur' }
  ],
  majorName: [
    { required: true, message: '请输入专业名称', trigger: 'blur' }
  ],
  grade: [
    { required: true, message: '请输入年级', trigger: 'blur' }
  ],
  contactPhone: [
    { required: true, message: '请输入联系电话', trigger: 'blur' }
  ],
  email: [
    { required: true, message: '请输入邮箱', trigger: 'blur' }
  ],
  verificationCode: [
    { required: true, message: '验证码不能为空', trigger: 'blur' }
  ]
});
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')
const formLabelWidth = ref<string>('')
const router = useRouter()

onMounted(() => {
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string, formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
});

const onReset = () => {
  if (studentRegisterFormRef.value) {
    studentRegisterFormRef.value.resetFields()
  }
  provinceCityArea.value = []
}

const refreshCaptcha = () => {
  studentRegisterForm.verificationCode = ''
  drawCaptcha()
}

const onRegister = () => {
  if (!studentRegisterFormRef.value) {
    return
  }
  studentRegisterFormRef.value.validate(async (valid: boolean) => {
    if (valid) {
      if (studentRegisterForm.password !== studentRegisterForm.password2) {
        ElMessage.error('两次输入的密码不一致，请重新输入')
        studentRegisterForm.password = ''
        studentRegisterForm.password2 = ''
        refreshCaptcha()
        return
      }
      if (generatedVerificationCode.value.toLowerCase() !== studentRegisterForm.verificationCode.toLowerCase()) {
        ElMessage.error('验证码错误')
        refreshCaptcha()
        return
      }
      loading.value = true
      const resp: Result<void> = await studentApi.save(studentRegisterForm)
      if (resp && resp.code === 1) {
        ElMessage.success('注册成功')
        await router.push({ path: '/Login', query: {type: 3} })
      } else {
        ElMessage.error('注册失败:' + (resp.msg ? resp.msg : ''))
        refreshCaptcha()
        loading.value = false
      }
    }
  })
}

const findMajor = () => {
  majorSelectorVisible.value = true
}

const handleMajorSelectedEvent = (selectedMajor: any) => {
  majorSelectorVisible.value = false
  if (selectedMajor && 'majorId' in selectedMajor && studentRegisterForm.majorId !== selectedMajor['majorId']) {
    studentRegisterForm.majorId = selectedMajor['majorId']
    studentRegisterForm.majorName = selectedMajor['majorName']
  }
}

const handleChange = (value: string[]) => {
  if (value && value.length > 0) {
    studentRegisterForm.province = value[0]
  }
  if (value && value.length > 1) {
    studentRegisterForm.city = value[1]
  }
  if (value && value.length > 2) {
    studentRegisterForm.area = value[1]
  }
}

const onBack = () => {
  router.push({ path: '/Login', query: {type: 3} })
}

</script>

<style lang="scss">
@import "@/assets/register.css";
</style>

// angular_ngzorro/src/app/student/student-register.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StudentService} from '../../service/student.service';
import {SharedModule} from '../shared.module';
import {StudentForm} from '../../types/req/StudentForm';
import {MajorSelectorComponent} from '../major/major-selector.component';
import areas from '../../const/area.json'
import {TITLE} from '../../const';
import {CaptchaComponent} from '../captcha/captcha.component';
import {Router} from '@angular/router';

@Component({
  selector: 'student-register',
  imports: [
    MajorSelectorComponent,
    SharedModule,
    CaptchaComponent
  ],
  templateUrl: './student-register.component.html',
  standalone: true,
  styleUrls: ['../../assets/register.less']
})
export class StudentRegisterComponent implements OnInit {
  studentToSave:StudentForm = {};
  studentForm!: FormGroup;
  verificationCode: string = '';
  saveLoading: boolean = false
  title: string = TITLE
  studentRegisterTitle: string = '学生注册'
  provinceCityAreaOptions = areas.provinces;

  @ViewChild(MajorSelectorComponent, { static: false }) majorSelectorComponent!: MajorSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private studentService: StudentService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.studentForm = this.fb.group({
      studentNumber: ['', [Validators.required]],
      name: ['', [Validators.required]],
      password: ['', [Validators.required]],
      password2: ['', [Validators.required]],
      gender: [undefined, [Validators.required]],
      birthDate: ['', [Validators.required]],
      majorId: [0],
      majorName: ['', [Validators.required]],
      grade: [2000, [Validators.required]],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      province: [''],
      city: [''],
      area: [''],
      provinceCityArea: [[]],
      address: [''],
      enrollmentDate: [''],
      graduationDate: [''],
      verificationCode: ['', [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.studentForm.controls) {
        this.studentForm.controls[i].markAsDirty();
        this.studentForm.controls[i].updateValueAndValidity();
      }
      if (!this.studentForm.valid) {
        this.saveLoading = false
        return
      }
      const formValue = this.studentForm.value;
      if (formValue.verificationCode.toLowerCase() !== this.verificationCode.toLowerCase()) {
        this.message.error('验证码错误');
        this.onReset()
        this.saveLoading = false
        return
      }
      this.studentService.save(Object.assign(this.studentToSave, formValue)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.router.navigate(['/login'], { queryParams: { type: 3 } })
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.studentForm.reset()
  }

  onBack() {
    this.router.navigate(['/login'])
  }

  findMajor() {
    this.majorSelectorComponent.display()
  }

  handleMajorSelectedEvent(selectedMajor: { majorId?: number; majorName?: string; }) {
    if (selectedMajor && 'majorId' in selectedMajor) {
      this.studentForm.patchValue(selectedMajor);
    }
  }
  onVerificationCodeGenerated(verificationCode: string): void {
    this.verificationCode = verificationCode
  }
}

<div class="register-page">
  <div class="register">
    <div class="login-title">{{ title }}</div>
    <div class="login-subtitle">{{ studentRegisterTitle }}</div>
    <form [formGroup]="studentForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentNumber" nzRequired>学号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入学号'">
              <input nz-input formControlName="studentNumber" placeholder="请输入学号" maxlength="20"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="gender" nzRequired>性别</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择性别'">
              <nz-select formControlName="gender">
                <nz-option nzLabel="男" [nzValue]="1"></nz-option>
                <nz-option nzLabel="女" [nzValue]="2"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入密码'">
              <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password2" nzRequired>确认密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请确认密码'">
              <input nz-input formControlName="password2" placeholder="请确认密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="birthDate" nzRequired>出生日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="birthDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="majorName" nzRequired>专业名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择专业名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="majorNameSuffixIconButton">
                <input nz-input formControlName="majorName" placeholder="请选择专业名称" readonly />
              </nz-input-group>
              <ng-template #majorNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findMajor()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="grade" nzRequired>年级</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入年级'">
              <nz-input-number formControlName="grade" [nzMin]="2000" [nzMax]="2100" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="enrollmentDate">入学日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="enrollmentDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入邮箱'">
              <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="graduationDate">毕业日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="graduationDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="area">省/市/区</nz-form-label>
            <nz-form-control>
              <nz-cascader [nzOptions]="provinceCityAreaOptions" formControlName="provinceCityArea"
                           nzValueProperty="code" nzLabelProperty="name"></nz-cascader>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label nzRequired [nzSpan]="4" nzFor="verificationCode">验证码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入验证码'">
              <input nz-input formControlName="verificationCode" placeholder="请输入验证码" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <div class="captcha-container">
              <app-captcha (verificationCodeGenerated)="onVerificationCodeGenerated($event)"></app-captcha>
            </div>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="8">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="address">家庭地址</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="address" placeholder="请输入家庭地址" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">注册</button>
      <button nz-button nzType="default" class="margin-button" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" class="margin-button" (click)="onBack()">返回登录</button>
    </div>
  </div>
</div>
<major-selector (majorSelectedEvent)="handleMajorSelectedEvent($event)"></major-selector>
