// v3_el/src/views/student/StudentSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="studentQueryForm" ref="studentQueryFormRef" :rules="rules">
        <el-form-item label="学号" prop="studentNumber">
          <el-input v-model="studentQueryForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
        </el-form-item>
        <el-form-item label="性别" prop="gender">
          <el-select v-model="studentQueryForm.gender" placeholder="请选择性别" class="select-custom">
            <el-option label="男" :value="1"></el-option>
            <el-option label="女" :value="2"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="专业名称" prop="majorName">
          <el-input v-model="studentQueryForm.majorName" placeholder="请选择专业名称" readonly="readonly">
            <template #suffix>
              <el-icon @click="findMajor"><Search/></el-icon>
            </template>
          </el-input>
        </el-form-item>
        <el-form-item label="年级" prop="grade">
          <el-input-number v-model="studentQueryForm.grade" :min="2000" :max="2100"></el-input-number>
        </el-form-item>
        <el-form-item label="联系电话" prop="contactPhone">
          <el-input v-model="studentQueryForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="state.tableData"
        border
        v-loading="state.loading"
        size="small"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="studentSelected">
        <el-table-column prop="studentNumber" label="学号"></el-table-column>
        <el-table-column prop="name" label="姓名"></el-table-column>
        <el-table-column prop="password" label="密码"></el-table-column>
        <el-table-column prop="gender" label="性别">
          <template v-slot="{ row }">
            <div v-if="row.gender === 1">男</div>
            <div v-if="row.gender === 2">女</div>
          </template>
        </el-table-column>
        <el-table-column prop="birthDate" label="出生日期"></el-table-column>
        <el-table-column prop="majorName" label="专业名称"></el-table-column>
        <el-table-column prop="grade" label="年级"></el-table-column>
        <el-table-column prop="contactPhone" label="联系电话"></el-table-column>
        <el-table-column prop="email" label="邮箱"></el-table-column>
        <el-table-column prop="provinceName" label="省"></el-table-column>
        <el-table-column prop="cityName" label="市"></el-table-column>
        <el-table-column prop="areaName" label="区"></el-table-column>
        <el-table-column prop="address" label="家庭地址"></el-table-column>
        <el-table-column prop="enrollmentDate" label="入学日期"></el-table-column>
        <el-table-column prop="graduationDate" label="毕业日期"></el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="changePage"
          :current-page="state.currentPage"
          :page-sizes="state.pageSizes"
          :page-size="state.pageSize"
          background
          layout="total, prev, pager, next, jumper"
          :total="state.total">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog v-model="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref, inject, toRefs, defineEmits} from 'vue';
import studentApi from '@/api/studentApi'
import type {StudentQueryForm} from "@/types/req/studentQueryForm";
import type {Student} from "@/types/resp/student";
import {ElMessage, ElMessageBox, type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";
import { Search } from '@element-plus/icons-vue';
import MajorSelector from "@/views/major/MajorSelector.vue";

const studentQueryFormRef = ref<FormInstance | null>(null);
let studentQueryForm = reactive<StudentQueryForm>({
  studentNumber: '',
  gender: undefined,
  majorId: 0,
  majorName: '',
  grade: 0,
  contactPhone: '',
})
const majorSelectorVisible = ref<boolean>(false)

const state = reactive({
  loading: false,
  tableData: [] as Student[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})

const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

const emit = defineEmits<{
  (e: 'studentSelectedEvent', data?: {
    studentId: number,
    studentNumber: string,
    }): void;
}>()

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<Student>> = await studentApi.find(studentQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
        const page: Page<Student> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (studentQueryFormRef.value) {
    studentQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const studentSelected = (row: Student) => {
  emit('studentSelectedEvent', {
    studentId: row.id,
    studentNumber: row.studentNumber,
  })
}

const findMajor = () => {
  majorSelectorVisible.value = true
}

const handleMajorSelectedEvent = (selectedMajor: any) => {
  majorSelectorVisible.value = false
  if (selectedMajor && 'majorId' in selectedMajor && studentQueryForm.majorId !== selectedMajor['majorId']) {
    studentQueryForm.majorId = selectedMajor['majorId']
    studentQueryForm.majorName = selectedMajor['majorName']
  }
}

const onBack = () => {
  emit('studentSelectedEvent')
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/student/student-selector.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StudentService} from '../../service/student.service';
import {StudentQueryForm} from '../../types/req/StudentQueryForm';
import {SharedModule} from '../shared.module';
import {Student} from '../../types/resp/Student';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';
import {MajorSelectorComponent} from '../major/major-selector.component';

@Component({
  selector: 'student-selector',
  imports: [
    MajorSelectorComponent,
    SharedModule
  ],
  templateUrl: './student-selector.component.html',
  standalone: true
})
export class StudentSelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: Student[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '学生信息选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(MajorSelectorComponent, { static: false }) majorSelectorComponent!: MajorSelectorComponent;

  @Output() studentSelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private studentService: StudentService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      studentNumber: [''],
      gender: [undefined],
      majorId: [0],
      majorName: [''],
      grade: [2000],
      contactPhone: [''],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.studentService.find(new StudentQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<Student> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: Student, event: MouseEvent) {
    this.isVisible = false
    this.studentSelectedEvent.emit({
      studentId: row.id,
      studentNumber: row.studentNumber,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

  findMajor() {
    this.majorSelectorComponent.display()
  }

  handleMajorSelectedEvent(selectedMajor: { majorId?: number; majorName?: string; }) {
    if (selectedMajor && 'majorId' in selectedMajor) {
      this.searchForm.patchValue(selectedMajor);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
      <nz-form-item>
        <nz-form-label nzFor="studentNumber">学号</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="studentNumber" placeholder="请输入学号" />
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="gender">性别</nz-form-label>
        <nz-form-control>
          <nz-select formControlName="gender" class="custom-select-width">
            <nz-option nzLabel="男" [nzValue]="1"></nz-option>
            <nz-option nzLabel="女" [nzValue]="2"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="majorName">专业名称</nz-form-label>
        <nz-form-control>
          <nz-input-group nzSearch [nzAddOnAfter]="majorNameSuffixIconButton">
            <input nz-input formControlName="majorName" placeholder="请选择专业名称" readonly />
          </nz-input-group>
          <ng-template #majorNameSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findMajor()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="grade">年级</nz-form-label>
        <nz-form-control>
        <nz-input-number formControlName="grade" nzMin="2000" nzMax="2100" />
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="contactPhone">联系电话</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" />
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small" [nzScroll]="{ x: 'auto' }">
      <thead>
        <tr>
          <th nzWidth="100px">学号</th>
          <th nzWidth="80px">姓名</th>
          <th nzWidth="100px">密码</th>
          <th nzWidth="60px">性别</th>
          <th nzWidth="100px">出生日期</th>
          <th nzWidth="150px">专业名称</th>
          <th nzWidth="80px">年级</th>
          <th nzWidth="120px">联系电话</th>
          <th nzWidth="180px">邮箱</th>
          <th nzWidth="80px">省</th>
          <th nzWidth="80px">市</th>
          <th nzWidth="80px">区</th>
          <th nzWidth="180px">家庭地址</th>
          <th nzWidth="120px">入学日期</th>
          <th nzWidth="120px">毕业日期</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.studentNumber}}</td>
          <td>{{data.name}}</td>
          <td>{{data.password}}</td>
          <td>
            <ng-container *ngIf="data.gender === 1">男</ng-container>
            <ng-container *ngIf="data.gender === 2">女</ng-container>
          </td>
          <td>{{data.birthDate}}</td>
          <td>{{data.majorName}}</td>
          <td>{{data.grade}}</td>
          <td>{{data.contactPhone}}</td>
          <td>{{data.email}}</td>
          <td>{{data.provinceName}}</td>
          <td>{{data.cityName}}</td>
          <td>{{data.areaName}}</td>
          <td>{{data.address}}</td>
          <td>{{data.enrollmentDate}}</td>
          <td>{{data.graduationDate}}</td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<major-selector (majorSelectedEvent)="handleMajorSelectedEvent($event)"></major-selector>
