// v2_el/src/views/student/StudentAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="studentForm" :label-width="formLabelWidth" ref="refStudentForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="学号" prop="studentNumber">
            <el-input v-model="studentForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="studentForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="密码" prop="password">
            <el-input v-model="studentForm.password" placeholder="请输入密码" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="性别" prop="gender">
            <el-select v-model="studentForm.gender" placeholder="请选择性别">
              <el-option label="男" :value="1"></el-option>
              <el-option label="女" :value="2"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="出生日期" prop="birthDate">
            <el-date-picker
                v-model="studentForm.birthDate" type="date" placeholder="出生日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="专业名称" prop="majorName">
            <el-input v-model="studentForm.majorName" placeholder="请选择专业名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findMajor"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="年级" prop="grade">
            <el-input-number v-model="studentForm.grade" :min="2000" :max="2100"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="contactPhone">
            <el-input v-model="studentForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="邮箱" prop="email">
            <el-input v-model="studentForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="省/市/区">
            <el-cascader
                v-model="provinceCityArea"
                :options="provinceCityAreaOptions"
                :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"
                @change="handleChange"></el-cascader>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="家庭地址" prop="address">
            <el-input v-model="studentForm.address" placeholder="请输入家庭地址" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="入学日期" prop="enrollmentDate">
            <el-date-picker
                v-model="studentForm.enrollmentDate" type="date" placeholder="入学日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="毕业日期" prop="graduationDate">
            <el-date-picker
                v-model="studentForm.graduationDate" type="date" placeholder="毕业日期" value-format="yyyy-MM-dd">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script>
import studentApi from '@/api/studentApi'
import MajorSelector from "@/views/major/MajorSelector.vue";
import areas from "@/locales/area.json";
export default {
  name: 'StudentAdd',
  components: {MajorSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      studentForm: {
        studentNumber: '',
        name: '',
        password: '',
        gender: '',
        birthDate: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: '',
        email: '',
        province: '',
        city: '',
        area: '',
        address: '',
        enrollmentDate: '',
        graduationDate: ''
      },
      rules: {
        studentNumber: [
          { required: true, message: '请输入学号', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '请输入密码', trigger: 'blur' }
        ],
        gender: [
          { required: true, message: '请输入性别', trigger: 'blur' }
        ],
        birthDate: [
          { required: true, message: '请输入出生日期', trigger: 'blur' }
        ],
        majorName: [
          { required: true, message: '请输入专业名称', trigger: 'blur' }
        ],
        grade: [
          { required: true, message: '请输入年级', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        email: [
          { required: true, message: '请输入邮箱', trigger: 'blur' }
        ],
      },
      majorSelectorVisible: false,
      provinceCityArea: [],
      provinceCityAreaOptions: areas.provinces
    }
  },
  created () {
    if (this.id) {
      studentApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.studentForm = resp.data
            this.provinceCityArea = []
            if (this.studentForm.province) {
              this.provinceCityArea.push(this.studentForm.province)
            }
            if (this.studentForm.city) {
              this.provinceCityArea.push(this.studentForm.city)
            }
            if (this.studentForm.area) {
              this.provinceCityArea.push(this.studentForm.area)
            }
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.studentForm = {
        studentNumber: '',
        name: '',
        password: '',
        gender: '',
        birthDate: '',
        majorId: '',
        majorName: '',
        grade: '',
        contactPhone: '',
        email: '',
        province: '',
        city: '',
        area: '',
        address: '',
        enrollmentDate: '',
        graduationDate: ''
      }
      this.provinceCityArea = []
      this.$emit('reset-student-add-event')
    },
    onSave () {
      this.$refs.refStudentForm.validate((valid) => {
        if (valid) {
          studentApi.save(this.studentForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-student-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findMajor () {
      this.majorSelectorVisible = true
    },
    handleMajorSelectedEvent (selectedMajor) {
      this.majorSelectorVisible = false
      if (selectedMajor && 'majorId' in selectedMajor && this.studentForm.majorId !== selectedMajor['majorId']) {
        this.studentForm.majorId = selectedMajor['majorId']
        this.studentForm.majorName = selectedMajor['majorName']
      }
    },
    handleChange(value) {
      if (value && value.length) {
        this.studentForm.province = value[0]
      }
      if (value && value.length > 1) {
        this.studentForm.city = value[1]
      }
      if (value && value.length > 2) {
        this.studentForm.area = value[2]
      }
    },
    onBack () {
      this.$emit('close-student-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/student/student-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StudentService} from '../../service/student.service';
import {SharedModule} from '../shared.module';
import {StudentForm} from '../../types/req/StudentForm';
import {MODAL_WIDTH} from '../../const'
import {MajorSelectorComponent} from '../major/major-selector.component';
import areas from '../../const/area.json'

@Component({
  selector: 'student-add',
  imports: [
    MajorSelectorComponent,
    SharedModule
  ],
  templateUrl: './student-add.component.html',
  standalone: true
})
export class StudentAddComponent implements OnInit {
  studentToSave:StudentForm = {};
  studentForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增学生信息'
  modalWidth: string = MODAL_WIDTH
  provinceCityAreaOptions = areas.provinces;

  @ViewChild(MajorSelectorComponent, { static: false }) majorSelectorComponent!: MajorSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private studentService: StudentService
  ) {}

  ngOnInit(): void {
    this.studentForm = this.fb.group({
      studentNumber: ['', [Validators.required]],
      name: ['', [Validators.required]],
      password: ['', [Validators.required]],
      gender: [undefined, [Validators.required]],
      birthDate: ['', [Validators.required]],
      majorId: [0],
      majorName: ['', [Validators.required]],
      grade: [2000, [Validators.required]],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      province: [''],
      city: [''],
      area: [''],
      provinceCityArea: [[]],
      address: [''],
      enrollmentDate: [''],
      graduationDate: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.studentForm.controls) {
        this.studentForm.controls[i].markAsDirty();
        this.studentForm.controls[i].updateValueAndValidity();
      }
      if (!this.studentForm.valid) {
        this.saveLoading = false
        return
      }
      this.studentService.save(Object.assign(this.studentToSave, this.studentForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增学生信息'.slice()
    this.studentForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改学生信息'
      this.saveLoading = true
      this.studentService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.studentToSave = resp.data
            const provinceCityArea = []
            if (this.studentToSave.province) {
              provinceCityArea.push(this.studentToSave.province)
            }
            if (this.studentToSave.city) {
              provinceCityArea.push(this.studentToSave.city)
            }
            if (this.studentToSave.area) {
              provinceCityArea.push(this.studentToSave.area)
            }
            this.studentForm.patchValue(Object.assign({provinceCityArea: provinceCityArea},this.studentToSave));
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findMajor() {
    this.majorSelectorComponent.display()
  }

  handleMajorSelectedEvent(selectedMajor: { majorId?: number; majorName?: string; }) {
    if (selectedMajor && 'majorId' in selectedMajor) {
      this.studentForm.patchValue(selectedMajor);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="studentForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentNumber" nzRequired>学号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入学号'">
              <input nz-input formControlName="studentNumber" placeholder="请输入学号" maxlength="20"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入密码'">
              <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="gender" nzRequired>性别</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择性别'">
              <nz-select formControlName="gender">
                <nz-option nzLabel="男" [nzValue]="1"></nz-option>
                <nz-option nzLabel="女" [nzValue]="2"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="birthDate">出生日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="birthDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="majorName" nzRequired>专业名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择专业名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="majorNameSuffixIconButton">
                <input nz-input formControlName="majorName" placeholder="请选择专业名称" readonly />
              </nz-input-group>
              <ng-template #majorNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findMajor()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="grade" nzRequired>年级</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入年级'">
            <nz-input-number formControlName="grade" [nzMin]="2000" [nzMax]="2100" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入联系电话'">
              <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入邮箱'">
              <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="area">省/市/区</nz-form-label>
            <nz-form-control>
              <nz-cascader [nzOptions]="provinceCityAreaOptions" formControlName="provinceCityArea"
                           nzValueProperty="code" nzLabelProperty="name"></nz-cascader>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="address">家庭地址</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="address" placeholder="请输入家庭地址" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="enrollmentDate">入学日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="enrollmentDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="graduationDate">毕业日期</nz-form-label>
            <nz-form-control >
              <nz-date-picker formControlName="graduationDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<major-selector (majorSelectedEvent)="handleMajorSelectedEvent($event)"></major-selector>
