// react_antd/src/pages/grade/GradeAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, InputNumber, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import gradeApi from "@/api/gradeApi.ts";
import {Grade} from "@/types/resp/grade";
import CourseSelector from "@/pages/course/CourseSelector.tsx";
import StudentSelector from "@/pages/student/StudentSelector.tsx";

interface GradeAddProps {
  visible: boolean;
  id: number;
  onCloseGradeAdd: () => void;
}

const GradeAdd: React.FC<GradeAddProps> = ({visible, id, onCloseGradeAdd}) => {

  const [form] = Form.useForm<Grade>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    courseName: [
      { required: true, message: '请输入课程名称' }
    ],
    studentNumber: [
      { required: true, message: '请输入学生学号' }
    ],
  };

  let gradeForm: Partial<Grade> = {}

  const [title, setTitle] = useState('新增成绩信息');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑成绩信息')
      initGradeFormById(id)
    } else {
      setTitle('新增成绩信息')
      form.resetFields();
    }
  }, [visible]);

  const initGradeFormById = async (id: number) => {
    const resp: Result<Grade> = await gradeApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      gradeForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let grade2Save:Grade = form.getFieldsValue()
      if (id) {
        grade2Save = Object.assign(gradeForm, grade2Save)
      }
      const resp: Result<void> = await gradeApi.save(grade2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增成绩信息')
    form.resetFields();
  };
  
  const [courseSelectorVisible, setCourseSelectorVisible] = useState(false);
  const findCourse = () => {
    setCourseSelectorVisible(true);
  }
  const handleCourseSelected = (selectedCourse: { courseId?: number; courseName?: string; }) => {
    setCourseSelectorVisible(false)
    if (selectedCourse && 'courseId' in selectedCourse) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      courseId: selectedCourse['courseId'],
      courseName: selectedCourse['courseName'],
      }));
    }
  };
  const handleCloseCourseSelector = () => {
    setCourseSelectorVisible(false)
  };
  const [studentSelectorVisible, setStudentSelectorVisible] = useState(false);
  const findStudent = () => {
    setStudentSelectorVisible(true);
  }
  const handleStudentSelected = (selectedStudent: { studentId?: number; studentNumber?: string; }) => {
    setStudentSelectorVisible(false)
    if (selectedStudent && 'studentId' in selectedStudent) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      studentId: selectedStudent['studentId'],
      studentNumber: selectedStudent['studentNumber'],
      }));
    }
  };
  const handleCloseStudentSelector = () => {
    setStudentSelectorVisible(false)
  };

  const onBack = () => {
    onCloseGradeAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseGradeAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="gradeForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="courseName" label="课程名称" rules={rules.courseName}>
              <Input.Search placeholder="请选择课程名称" onSearch={findCourse} readOnly={true} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="studentNumber" label="学生学号" rules={rules.studentNumber}>
              <Input.Search placeholder="请选择学生学号" onSearch={findStudent} readOnly={true} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="grade" label="成绩">
              <InputNumber min={1} max={999} precision={2} step={0.1} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
      <CourseSelector visible={courseSelectorVisible} onCourseSelected={handleCourseSelected} onCloseCourseSelector={handleCloseCourseSelector} />
      <StudentSelector visible={studentSelectorVisible} onStudentSelected={handleStudentSelected} onCloseStudentSelector={handleCloseStudentSelector} />
    </Modal>
  )
}

export default GradeAdd;

// v2_el/src/views/grade/GradeAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="gradeForm" :label-width="formLabelWidth" ref="refGradeForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="课程名称" prop="courseName">
            <el-input v-model="gradeForm.courseName" placeholder="请选择课程名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findCourse"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="学生学号" prop="studentNumber">
            <el-input v-model="gradeForm.studentNumber" placeholder="请选择学生学号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStudent"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="成绩" prop="grade">
            <el-input-number v-model="gradeForm.grade" :precision="2" :step="0.1" :min="1" :max="999"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="courseSelectorVisible" v-if="courseSelectorVisible" title="课程信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <course-selector @course-selected-event="handleCourseSelectedEvent">
      </course-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentSelectorVisible" v-if="studentSelectorVisible" title="学生信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <student-selector @student-selected-event="handleStudentSelectedEvent">
      </student-selector>
    </el-dialog>
  </div>
</template>

<script>
import gradeApi from '@/api/gradeApi'
import CourseSelector from "@/views/course/CourseSelector.vue";
import StudentSelector from "@/views/student/StudentSelector.vue";
export default {
  name: 'GradeAdd',
  components: {CourseSelector,StudentSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      gradeForm: {
        courseId: '',
        courseName: '',
        studentId: '',
        studentNumber: '',
        grade: ''
      },
      rules: {
        courseName: [
          { required: true, message: '请输入课程名称', trigger: 'blur' }
        ],
        studentNumber: [
          { required: true, message: '请输入学生学号', trigger: 'blur' }
        ],
      },
      courseSelectorVisible: false,
      studentSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      gradeApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.gradeForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.gradeForm = {
        courseId: '',
        courseName: '',
        studentId: '',
        studentNumber: '',
        grade: ''
      }
      this.$emit('reset-grade-add-event')
    },
    onSave () {
      this.$refs.refGradeForm.validate((valid) => {
        if (valid) {
          gradeApi.save(this.gradeForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-grade-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findCourse () {
      this.courseSelectorVisible = true
    },
    handleCourseSelectedEvent (selectedCourse) {
      this.courseSelectorVisible = false
      if (selectedCourse && 'courseId' in selectedCourse && this.gradeForm.courseId !== selectedCourse['courseId']) {
        this.gradeForm.courseId = selectedCourse['courseId']
        this.gradeForm.courseName = selectedCourse['courseName']
      }
    },
    findStudent () {
      this.studentSelectorVisible = true
    },
    handleStudentSelectedEvent (selectedStudent) {
      this.studentSelectorVisible = false
      if (selectedStudent && 'studentId' in selectedStudent && this.gradeForm.studentId !== selectedStudent['studentId']) {
        this.gradeForm.studentId = selectedStudent['studentId']
        this.gradeForm.studentNumber = selectedStudent['studentNumber']
      }
    },
    onBack () {
      this.$emit('close-grade-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
