// react_antd/src/pages/university/UniversityView.tsx
import React, {useEffect} from "react";
import {Button, Cascader, Col, DatePicker, Form, Input, Modal, Row} from "antd";
import {University} from "@/types/resp/university";
import type {AreaOption} from "@/types/areaOption.ts";
import areas from "@/locales/area.json";

interface UniversityViewProps {
  visible: boolean;
  viewRow: object;
  onCloseUniversityView: () => void;
}

const UniversityView: React.FC<UniversityViewProps> = ({visible, viewRow, onCloseUniversityView}) => {

  const [form] = Form.useForm<University>();

  const provinceCityAreaOptions: AreaOption[] = areas.provinces

  const onBack = () => {
    onCloseUniversityView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      const provinceCityArea2 = []
      if ('province' in viewRow && typeof viewRow.province === 'string') {
        provinceCityArea2.push(viewRow.province)
      }
      if ('city' in viewRow && typeof viewRow.city === 'string') {
        provinceCityArea2.push(viewRow.city)
      }
      if ('area' in viewRow && typeof viewRow.area === 'string') {
        provinceCityArea2.push(viewRow.area)
      }
      form.setFieldsValue({...viewRow, provinceCityArea: provinceCityArea2});
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"学校信息详情"} open={visible} onCancel={onCloseUniversityView} width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="学校名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="establishmentDate" label="成立日期">
              <DatePicker/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="contactPhone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="email" label="邮箱">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="provinceCityArea" label="省/市/区">
              <Cascader options={provinceCityAreaOptions} fieldNames={{ label: "name", value: "code" }} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="location" label="地址">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={22}>
            <Form.Item name="universityDescription" label="学校简介" labelCol={{span: 3}}>
              <Input.TextArea autoSize={{ minRows: 5, maxRows: 5 }}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default UniversityView;

// v3_el/src/views/university/UniversityView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="universityForm" :label-width="formLabelWidth" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="学校名称">
            <el-input v-model="universityForm.name"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="成立日期">
            <el-input v-model="universityForm.establishmentDate"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话">
            <el-input v-model="universityForm.contactPhone"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="邮箱">
            <el-input v-model="universityForm.email"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="省/市/区">
            <el-cascader
              v-model="provinceCityArea"
              :options="provinceCityAreaOptions"
              :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"/>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="地址">
            <el-input v-model="universityForm.location"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="22">
          <el-form-item label="学校简介" prop="universityDescription">
            <el-input v-model="universityForm.universityDescription" placeholder="请输入学校简介" type="textarea" :rows="5" maxlength="65535"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="universityForm.createTime"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="最后修改时间">
            <el-input v-model="universityForm.modifyTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import {defineEmits, defineProps, onMounted, reactive, ref, inject, toRefs} from 'vue';
import universityApi from '@/api/universityApi'
import type {University} from "@/types/resp/university";
import type {Id} from "@/types/id"
import areas from "@/locales/area.json";

const universityForm = reactive<Partial<University>>({});
const props = defineProps<Id>()
const provinceCityArea = ref<string[]>([])
const provinceCityAreaOptions = areas.provinces
const emit = defineEmits<{
  (e: 'closeUniversityViewEvent'): void;
}>()
const formLabelWidth = ref<string>('')

onMounted(() => {
  initUniversityById(props.id)
  const globalState = inject('globalState', {} as { formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
})

const initUniversityById = async (id: number) => {
  const resp = await universityApi.findById(id)
  if (resp && resp.code === 1 && resp.data) {
    Object.assign(universityForm, resp.data)
    provinceCityArea.value = []
    if (universityForm.province) {
      provinceCityArea.value.push(universityForm.province)
    }
    if (universityForm.city) {
      provinceCityArea.value.push(universityForm.city)
    }
    if (universityForm.area) {
      provinceCityArea.value.push(universityForm.area)
    }
  }
}
const onBack = () => {
  emit('closeUniversityViewEvent')
}
</script>

<style lang="scss">
</style>
