// react_antd/src/pages/university/UniversityList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {University} from "@/types/resp/university";
import universityApi from '@/api/universityApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import UniversityAdd from "@/pages/university/UniversityAdd";
import UniversityView from "@/pages/university/UniversityView";


const UniversityList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '学校信息列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<University[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<University>> = await universityApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<University> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<University>['columns'] = [
    {title: '学校名称', dataIndex: 'name', key: 'name'},
    {title: '成立日期', key: 'establishmentDate', render: (_, record) => (
      <div>{record.establishmentDate.format('YYYY-MM-DD')}</div>
    )},
    {title: '联系电话', dataIndex: 'contactPhone', key: 'contactPhone'},
    {title: '邮箱', dataIndex: 'email', key: 'email'},
    {title: '省', dataIndex: 'provinceName', key: 'province'},
    {title: '市', dataIndex: 'cityName', key: 'city'},
    {title: '区', dataIndex: 'areaName', key: 'area'},
    {title: '地址', dataIndex: 'location', key: 'location'},
    {title: '学校简介', dataIndex: 'universityDescription', key: 'universityDescription', ellipsis: true},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [universityAddVisible, setUniversityAddVisible] = useState(false);
  const [universityViewVisible, setUniversityViewVisible] = useState(false);
  const [selectedUniversityId, setSelectedUniversityId] = useState(0)
  const [selectedUniversity, setSelectedUniversity] = useState({})

  const onAdd = () => {
    setSelectedUniversityId(0)
    setUniversityAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedUniversityId(id)
    setUniversityAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      universityApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: University) => {
    setSelectedUniversity(record)
    setUniversityViewVisible(true)
  };

  const handleCloseUniversityAdd = () => {
    setUniversityAddVisible(false)
  };

  const handleCloseUniversityView = () => {
    setUniversityViewVisible(false)
  };

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="universityList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="学校名称">
          <Input maxLength={64} placeholder="请输入学校名称"/>
        </Form.Item>
        <Form.Item name="location" label="地址">
          <Input maxLength={255} placeholder="请输入地址"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
      </Form>
      <Table<University> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <UniversityAdd visible={universityAddVisible} onCloseUniversityAdd={handleCloseUniversityAdd} id={selectedUniversityId} />
      <UniversityView visible={universityViewVisible} onCloseUniversityView={handleCloseUniversityView} viewRow={selectedUniversity} />
    </div>
  );
};

export default UniversityList;

// v3_el/src/views/university/UniversityList.vue
<template>
  <div class="university-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>学校信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="universityQueryForm" ref="universityQueryFormRef" :rules="rules">
      <el-form-item label="学校名称" prop="name">
        <el-input v-model="universityQueryForm.name" placeholder="请输入学校名称" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="地址" prop="location">
        <el-input v-model="universityQueryForm.location" placeholder="请输入地址" maxlength="255"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="name" label="学校名称"></el-table-column>
      <el-table-column prop="establishmentDate" label="成立日期"></el-table-column>
      <el-table-column prop="contactPhone" label="联系电话"></el-table-column>
      <el-table-column prop="email" label="邮箱"></el-table-column>
      <el-table-column prop="provinceName" label="省"></el-table-column>
      <el-table-column prop="cityName" label="市"></el-table-column>
      <el-table-column prop="areaName" label="区"></el-table-column>
      <el-table-column prop="location" label="地址"></el-table-column>
      <el-table-column label="学校简介">
        <template v-slot="{ row }">
          <div class="ellipsis">
            {{ row.universityDescription }}
          </div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="universityAddVisible" v-if="universityAddVisible" :title="universityAddTitle" :top="dialogTop" :width="dialogWidth">
      <university-add :id="selectedUniversityId" @close-university-add-event="handleCloseUniversityAddEvent" @reset-university-add-event="handleResetUniversityAddEvent">
      </university-add>
    </el-dialog>
    <el-dialog v-model="universityViewVisible" v-if="universityViewVisible" title="学校信息详情" :top="dialogTop" :width="dialogWidth">
      <university-view :id="selectedUniversityId" @close-university-view-event="handleCloseUniversityViewEvent">
      </university-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref, inject, toRefs} from 'vue';
import universityApi from '@/api/universityApi'
import type {UniversityQueryForm} from "@/types/req/universityQueryForm";
import type {University} from "@/types/resp/university";
import {ElMessage, ElMessageBox, type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";
import UniversityAdd from "@/views/university/UniversityAdd.vue"
import UniversityView from "@/views/university/UniversityView.vue"

const universityQueryFormRef = ref<FormInstance | null>(null);
let universityQueryForm = reactive<UniversityQueryForm>({
  name: '',
  location: '',
})

const state = reactive({
  loading: false,
  tableData: [] as University[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedUniversityId = ref<number>(0)
const universityAddVisible = ref<boolean>(false)
const universityViewVisible = ref<boolean>(false)
const universityAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<University>> = await universityApi.find(universityQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<University> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (universityQueryFormRef.value) {
    universityQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedUniversityId.value = 0
  universityAddVisible.value = true
  universityAddTitle.value = '学校信息新增'
}
const editRow = (id: number) => {
  selectedUniversityId.value = id
  universityAddVisible.value = true
  universityAddTitle.value = '学校信息编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    universityApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedUniversityId.value = id
  universityViewVisible.value = true
}


const handleCloseUniversityViewEvent = () => {
  universityViewVisible.value = false
}

const handleResetUniversityAddEvent = () => {
  universityAddTitle.value = '学校信息新增'
}

const handleCloseUniversityAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  universityAddVisible.value = false
}
</script>

<style lang="scss">
</style>
