// angular_ngzorro/src/app/student/student-personal-info.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StudentService} from '../../service/student.service';
import {SharedModule} from '../shared.module';
import {StudentForm} from '../../types/req/StudentForm';
import {MODAL_WIDTH} from '../../const'
import {MajorSelectorComponent} from '../major/major-selector.component';
import areas from '../../const/area.json'

@Component({
  selector: 'student-personal-info',
  imports: [
    MajorSelectorComponent,
    SharedModule
  ],
  templateUrl: './student-personal-info.component.html',
  standalone: true
})
export class StudentPersonalInfoComponent implements OnInit {
  studentToSave:StudentForm = {};
  studentForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增学生信息'
  modalWidth: string = MODAL_WIDTH
  provinceCityAreaOptions = areas.provinces;

  @ViewChild(MajorSelectorComponent, { static: false }) majorSelectorComponent!: MajorSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private studentService: StudentService
  ) {}

  ngOnInit(): void {
    this.studentForm = this.fb.group({
      studentNumber: ['', [Validators.required]],
      name: ['', [Validators.required]],
      password: ['', [Validators.required]],
      gender: [undefined, [Validators.required]],
      birthDate: ['', [Validators.required]],
      majorId: [0],
      majorName: ['', [Validators.required]],
      grade: [2000, [Validators.required]],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      province: [''],
      city: [''],
      area: [''],
      provinceCityArea: [[]],
      address: [''],
      enrollmentDate: [''],
      graduationDate: [''],
    })

    this.display(1)
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.studentForm.controls) {
        this.studentForm.controls[i].markAsDirty();
        this.studentForm.controls[i].updateValueAndValidity();
      }
      if (!this.studentForm.valid) {
        this.saveLoading = false
        return
      }
      this.studentService.save(Object.assign(this.studentToSave, this.studentForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增学生信息'.slice()
    this.studentForm.reset()
  }

  display(id: number) {
    this.studentService.findById(id).subscribe({
      next: (resp) => {
        if (resp && resp.code === 1 && resp.data) {
          this.studentToSave = resp.data
          const provinceCityArea = []
          if (this.studentToSave.province) {
            provinceCityArea.push(this.studentToSave.province)
          }
          if (this.studentToSave.city) {
            provinceCityArea.push(this.studentToSave.city)
          }
          if (this.studentToSave.area) {
            provinceCityArea.push(this.studentToSave.area)
          }
          this.studentForm.patchValue(Object.assign({provinceCityArea: provinceCityArea},this.studentToSave));
        }
      },
      complete: () => {
        this.saveLoading = false
      }
    })
  }

  findMajor() {
    this.majorSelectorComponent.display()
  }

  handleMajorSelectedEvent(selectedMajor: { majorId?: number; majorName?: string; }) {
    if (selectedMajor && 'majorId' in selectedMajor) {
      this.studentForm.patchValue(selectedMajor);
    }
  }
}

<nz-breadcrumb class="breadcrumb">
  <nz-breadcrumb-item>
    <a routerLink="/Home">主页</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>学生个人信息</nz-breadcrumb-item>
</nz-breadcrumb>
<form [formGroup]="studentForm" (keydown.enter)="$event.preventDefault()">
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="studentNumber" nzRequired>学号</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入学号'">
          <input nz-input formControlName="studentNumber" placeholder="请输入学号" maxlength="20"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入姓名'">
          <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入密码'">
          <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="gender" nzRequired>性别</nz-form-label>
        <nz-form-control [nzErrorTip]="'请选择性别'">
          <nz-select formControlName="gender">
            <nz-option nzLabel="男" [nzValue]="1"></nz-option>
            <nz-option nzLabel="女" [nzValue]="2"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="birthDate">出生日期</nz-form-label>
        <nz-form-control >
          <nz-date-picker formControlName="birthDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="majorName" nzRequired>专业名称</nz-form-label>
        <nz-form-control [nzErrorTip]="'请选择专业名称'">
          <nz-input-group nzSearch [nzAddOnAfter]="majorNameSuffixIconButton">
            <input nz-input formControlName="majorName" placeholder="请选择专业名称" readonly />
          </nz-input-group>
          <ng-template #majorNameSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findMajor()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="grade" nzRequired>年级</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入年级'">
          <nz-input-number formControlName="grade" [nzMin]="2000" [nzMax]="2100" />
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入联系电话'">
          <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入邮箱'">
          <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="area">省/市/区</nz-form-label>
        <nz-form-control>
          <nz-cascader [nzOptions]="provinceCityAreaOptions" formControlName="provinceCityArea"
                       nzValueProperty="code" nzLabelProperty="name"></nz-cascader>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="address">家庭地址</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="address" placeholder="请输入家庭地址" maxlength="255"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="enrollmentDate">入学日期</nz-form-label>
        <nz-form-control >
          <nz-date-picker formControlName="enrollmentDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="graduationDate">毕业日期</nz-form-label>
        <nz-form-control >
          <nz-date-picker formControlName="graduationDate" nzFormat="yyyy-MM-dd"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
</form>
<div class="form-button-container">
  <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
</div>
<major-selector (majorSelectedEvent)="handleMajorSelectedEvent($event)"></major-selector>

// v3_el/src/views/student/StudentPersonalInfo.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form label-position="right" :model="studentForm" :label-width="formLabelWidth" ref="studentFormRef" :rules="rules">
        <el-row>
          <el-col :span="11">
            <el-form-item label="学号" prop="studentNumber">
              <el-input v-model="studentForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="studentForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="密码" prop="password">
              <el-input v-model="studentForm.password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="性别" prop="gender">
              <el-select v-model="studentForm.gender" placeholder="请选择性别">
                <el-option label="男" :value="1"></el-option>
                <el-option label="女" :value="2"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="出生日期" prop="birthDate">
              <el-date-picker
                v-model="studentForm.birthDate" type="date" placeholder="出生日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="专业名称" prop="majorName">
              <el-input v-model="studentForm.majorName" placeholder="请选择专业名称" readonly="readonly">
                <template #suffix>
                  <el-icon @click="findMajor"><Search/></el-icon>
                </template>
              </el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="年级" prop="grade">
              <el-input-number v-model="studentForm.grade" :min="2000" :max="2100"></el-input-number>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="联系电话" prop="contactPhone">
              <el-input v-model="studentForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="studentForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="省/市/区">
              <el-cascader
                v-model="provinceCityArea"
                :options="provinceCityAreaOptions"
                :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"
                @change="handleChange"/>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="家庭地址" prop="address">
              <el-input v-model="studentForm.address" placeholder="请输入家庭地址" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="入学日期" prop="enrollmentDate">
              <el-date-picker
                v-model="studentForm.enrollmentDate" type="date" placeholder="入学日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="毕业日期" prop="graduationDate">
              <el-date-picker
                v-model="studentForm.graduationDate" type="date" placeholder="毕业日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog v-model="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {defineEmits, inject, onMounted, reactive, ref, toRefs} from 'vue';
import studentApi from '@/api/studentApi'
import type {FormInstance} from 'element-plus';
import {ElMessage} from 'element-plus'
import type {StudentForm} from "@/types/req/studentForm";
import type {Result} from '@/types/result'
import type {Student} from "@/types/resp/student";
import {Search} from '@element-plus/icons-vue';
import MajorSelector from "@/views/major/MajorSelector.vue";
import areas from "@/locales/area.json";

const studentFormRef = ref<FormInstance | null>(null);
let studentForm = reactive<StudentForm>({
  studentNumber: '',
  name: '',
  password: '',
  gender: undefined,
  birthDate: '',
  majorId: 0,
  majorName: '',
  grade: 0,
  contactPhone: '',
  email: '',
  province: '',
  city: '',
  area: '',
  address: '',
  enrollmentDate: '',
  graduationDate: '',
})
const provinceCityArea = ref<string[]>([])
const provinceCityAreaOptions = areas.provinces
const majorSelectorVisible = ref<boolean>(false)
const emit = defineEmits<{
  (e: 'resetStudentAddEvent'): void;
  (e: 'closeStudentAddEvent', data?: { search: boolean }): void;
}>()

const rules = reactive({
  studentNumber: [
    { required: true, message: '请输入学号', trigger: 'blur' }
  ],
  name: [
    { required: true, message: '请输入姓名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' }
  ],
  gender: [
    { required: true, message: '请输入性别', trigger: 'blur' }
  ],
  birthDate: [
    { required: true, message: '请输入出生日期', trigger: 'blur' }
  ],
  majorName: [
    { required: true, message: '请输入专业名称', trigger: 'blur' }
  ],
  grade: [
    { required: true, message: '请输入年级', trigger: 'blur' }
  ],
  contactPhone: [
    { required: true, message: '请输入联系电话', trigger: 'blur' }
  ],
  email: [
    { required: true, message: '请输入邮箱', trigger: 'blur' }
  ],
});
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')
const formLabelWidth = ref<string>('')

onMounted(() => {

  initStudentFormById(1)

  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string, formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
});

const initStudentFormById = async (id: number) => {
  const resp: Result<Student> = await studentApi.findById(id)
  if (resp && resp.code === 1 && resp.data) {
    Object.assign(studentForm, resp.data)
    provinceCityArea.value = []
    if (studentForm.province) {
      provinceCityArea.value.push(studentForm.province)
    }
    if (studentForm.city) {
      provinceCityArea.value.push(studentForm.city)
    }
    if (studentForm.area) {
      provinceCityArea.value.push(studentForm.area)
    }
  }
}

const onReset = () => {
  if (studentFormRef.value) {
    studentFormRef.value.resetFields()
  }
  provinceCityArea.value = []
}

const onSave = () => {
  if (!studentFormRef.value) {
    return
  }
  studentFormRef.value.validate(async (valid: boolean) => {
    if (valid) {
      const resp: Result<void> = await studentApi.save(studentForm)
      if (resp && resp.code === 1) {
        ElMessage.success('保存成功')
      } else {
        ElMessage.error('保存失败:' + (resp.msg ? resp.msg : ''))
      }
    }
  })
}

const findMajor = () => {
  majorSelectorVisible.value = true
}

const handleMajorSelectedEvent = (selectedMajor: any) => {
  majorSelectorVisible.value = false
  if (selectedMajor && 'majorId' in selectedMajor && studentForm.majorId !== selectedMajor['majorId']) {
    studentForm.majorId = selectedMajor['majorId']
    studentForm.majorName = selectedMajor['majorName']
  }
}

const handleChange = (value: string[]) => {
  if (value && value.length > 0) {
    studentForm.province = value[0]
  }
  if (value && value.length > 1) {
    studentForm.city = value[1]
  }
  if (value && value.length > 2) {
    studentForm.area = value[1]
  }
}

</script>

<style lang="scss">
</style>
