// v2_el/src/views/university/UniversityList.vue
<template>
  <div class="university-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>学校信息列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="searchParams">
      <el-form-item label="学校名称">
        <el-input v-model="searchParams.name" placeholder="请输入学校名称" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="地址">
        <el-input v-model="searchParams.location" placeholder="请输入地址" maxlength="255"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="pageData.list"
      border
      v-loading="pageData.loading"
      size="mini"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="name" label="学校名称"></el-table-column>
      <el-table-column prop="establishmentDate" label="成立日期"></el-table-column>
      <el-table-column prop="contactPhone" label="联系电话"></el-table-column>
      <el-table-column prop="email" label="邮箱"></el-table-column>
      <el-table-column prop="provinceName" label="省"></el-table-column>
      <el-table-column prop="cityName" label="市"></el-table-column>
      <el-table-column prop="areaName" label="区"></el-table-column>
      <el-table-column prop="location" label="地址"></el-table-column>
      <el-table-column label="学校简介">
        <template v-slot="{ row }">
          <div class="ellipsis">
            {{ row.universityDescription }}
          </div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="paginationChange"
        :current-page="pageData.current"
        :page-sizes="pageData.pageSizes"
        :page-size="pageData.size"
        background
        layout="total, prev, pager, next, jumper"
        :total="pageData.count">
      </el-pagination>
    </div>
    <el-dialog :visible.sync="universityAddVisible" v-if="universityAddVisible" :title="universityAddTitle" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <university-add :id="selectedUniversityId" @close-university-add-event="handleCloseUniversityAddEvent" @reset-university-add-event="handleResetUniversityAddEvent">
      </university-add>
    </el-dialog>
    <el-dialog :visible.sync="universityViewVisible" v-if="universityViewVisible" title="学校信息详情" :top="dialogTop" :width="dialogWidth">
      <university-view :id="selectedUniversityId" @close-university-view-event="handleCloseUniversityViewEvent">
      </university-view>
    </el-dialog>
  </div>
</template>

<script>
import universityApi from '@/api/universityApi'
import UniversityAdd from "@/views/university/UniversityAdd.vue"
import UniversityView from "@/views/university/UniversityView.vue"
import listQueryMixin from '@/mixins/listQueryMixin'
export default {
  name: 'UniversityList',
  components: {UniversityAdd, UniversityView},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        name: '',
        location: ''
      },
      universityAddVisible: false,
      universityAddTitle: '',
      universityViewVisible: false,
      selectedUniversityId: 0
    }
  },
  methods: {
    getPageData (p) {
      return universityApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        name: '',
        location: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    onAdd () {
      this.selectedUniversityId = ''
      this.universityAddVisible = true
      this.universityAddTitle = '学校信息新增'
    },
    editRow (id) {
      this.selectedUniversityId = id
      this.universityAddVisible = true
      this.universityAddTitle = '学校信息编辑'
    },
    delRow (id) {
      if (!id) {
        return
      }
      this.$confirm('确定要删除吗?', '删除提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        universityApi.del(id)
          .then((resp) => {
            if (resp && resp.code === 1) {
              this.$message.success('删除成功!')
              this.onSearch()
            } else {
              this.$message.error('删除失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          })
          .catch(error => {
            console.error('操作失败:', error)
          })
      }).catch(() => {})
    },
    detailRow (id) {
      this.selectedUniversityId = id
      this.universityViewVisible = true
    },
    handleCloseUniversityViewEvent () {
      this.universityViewVisible = false
    },
    handleResetUniversityAddEvent () {
      this.universityAddTitle = '学校信息新增'
    },
    handleCloseUniversityAddEvent (params) {
      if (params && params.search) {
        this.onSearch()
      }
      this.universityAddVisible = false
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/university/UniversityList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {University} from "@/types/resp/university";
import universityApi from '@/api/universityApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import UniversityAdd from "@/pages/university/UniversityAdd";
import UniversityView from "@/pages/university/UniversityView";


const UniversityList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '学校信息列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<University[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<University>> = await universityApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<University> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<University>['columns'] = [
    {title: '学校名称', dataIndex: 'name', key: 'name'},
    {title: '成立日期', key: 'establishmentDate', render: (_, record) => (
      <div>{record.establishmentDate.format('YYYY-MM-DD')}</div>
    )},
    {title: '联系电话', dataIndex: 'contactPhone', key: 'contactPhone'},
    {title: '邮箱', dataIndex: 'email', key: 'email'},
    {title: '省', dataIndex: 'provinceName', key: 'province'},
    {title: '市', dataIndex: 'cityName', key: 'city'},
    {title: '区', dataIndex: 'areaName', key: 'area'},
    {title: '地址', dataIndex: 'location', key: 'location'},
    {title: '学校简介', dataIndex: 'universityDescription', key: 'universityDescription', ellipsis: true},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [universityAddVisible, setUniversityAddVisible] = useState(false);
  const [universityViewVisible, setUniversityViewVisible] = useState(false);
  const [selectedUniversityId, setSelectedUniversityId] = useState(0)
  const [selectedUniversity, setSelectedUniversity] = useState({})

  const onAdd = () => {
    setSelectedUniversityId(0)
    setUniversityAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedUniversityId(id)
    setUniversityAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      universityApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: University) => {
    setSelectedUniversity(record)
    setUniversityViewVisible(true)
  };

  const handleCloseUniversityAdd = () => {
    setUniversityAddVisible(false)
  };

  const handleCloseUniversityView = () => {
    setUniversityViewVisible(false)
  };

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="universityList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="学校名称">
          <Input maxLength={64} placeholder="请输入学校名称"/>
        </Form.Item>
        <Form.Item name="location" label="地址">
          <Input maxLength={255} placeholder="请输入地址"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
      </Form>
      <Table<University> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <UniversityAdd visible={universityAddVisible} onCloseUniversityAdd={handleCloseUniversityAdd} id={selectedUniversityId} />
      <UniversityView visible={universityViewVisible} onCloseUniversityView={handleCloseUniversityView} viewRow={selectedUniversity} />
    </div>
  );
};

export default UniversityList;
