// angular_ngzorro/src/app/university/university-selector.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {UniversityService} from '../../service/university.service';
import {UniversityQueryForm} from '../../types/req/UniversityQueryForm';
import {SharedModule} from '../shared.module';
import {University} from '../../types/resp/University';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';

@Component({
  selector: 'university-selector',
  imports: [
    SharedModule
  ],
  templateUrl: './university-selector.component.html',
  standalone: true
})
export class UniversitySelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: University[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '学校信息选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH


  @Output() universitySelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private universityService: UniversityService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      name: [''],
      location: [''],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.universityService.find(new UniversityQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<University> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: University, event: MouseEvent) {
    this.isVisible = false
    this.universitySelectedEvent.emit({
      universityId: row.id,
      universityName: row.name,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
      <nz-form-item>
        <nz-form-label nzFor="name">学校名称</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="name" placeholder="请输入学校名称" />
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="location">地址</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="location" placeholder="请输入地址" />
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
      <thead>
        <tr>
          <th>学校名称</th>
          <th>成立日期</th>
          <th>联系电话</th>
          <th>邮箱</th>
          <th>省</th>
          <th>市</th>
          <th>区</th>
          <th>地址</th>
          <th>学校简介</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.name}}</td>
          <td>{{data.establishmentDate}}</td>
          <td>{{data.contactPhone}}</td>
          <td>{{data.email}}</td>
          <td>{{data.provinceName}}</td>
          <td>{{data.cityName}}</td>
          <td>{{data.areaName}}</td>
          <td>{{data.location}}</td>
          <td class="ellipsis">{{data.universityDescription}}</td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/university/UniversitySelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Table, TableProps} from 'antd';
import type {University} from "@/types/resp/university";
import universityApi from '@/api/universityApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";


interface UniversitySelectorProps {
  visible: boolean;
  onUniversitySelected: (selectedUniversity: { universityId?: number; universityName?: string }) => void;
  onCloseUniversitySelector: () => void;
}

const UniversitySelector: React.FC<UniversitySelectorProps> = ({visible, onUniversitySelected, onCloseUniversitySelector}) => {

  const [universitySelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    universitySelectorForm.resetFields();
  };

  const [data, setData] = useState<University[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<University>> = await universityApi.find(universitySelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<University> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<University>['columns'] = [
    {title: '学校名称', dataIndex: 'name', key: 'name'},
    {title: '成立日期', key: 'establishmentDate', render: (_, record) => (
        <div>{record.establishmentDate.format('YYYY-MM-DD')}</div>
      )},
    {title: '联系电话', dataIndex: 'contactPhone', key: 'contactPhone'},
    {title: '邮箱', dataIndex: 'email', key: 'email'},
    {title: '省', dataIndex: 'provinceName', key: 'province'},
    {title: '市', dataIndex: 'cityName', key: 'city'},
    {title: '区', dataIndex: 'areaName', key: 'area'},
    {title: '地址', dataIndex: 'location', key: 'location'},
    {title: '学校简介', dataIndex: 'universityDescription', key: 'universityDescription', ellipsis: true}
  ];

// 行双击事件处理器
  const handleRowDoubleClick = (row: University) => {
    onUniversitySelected({
      universityId: row.id,
      universityName: row.name,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseUniversitySelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);

  return (
    <Modal title={"学校信息选择器(双击行选中)"} open={visible} onCancel={onCloseUniversitySelector} width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={universitySelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="学校名称">
          <Input maxLength={64} placeholder="请输入学校名称"/>
        </Form.Item>
        <Form.Item name="location" label="地址">
          <Input maxLength={255} placeholder="请输入地址"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<University> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
    </Modal>
  );
};

export default UniversitySelector;
