// angular_ngzorro/src/app/teacher/teacher-personal-info.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {TeacherService} from '../../service/teacher.service';
import {SharedModule} from '../shared.module';
import {TeacherForm} from '../../types/req/TeacherForm';
import {MODAL_WIDTH} from '../../const'
import {FacultySelectorComponent} from '../faculty/faculty-selector.component';

@Component({
  selector: 'teacher-personal-info',
  imports: [
    FacultySelectorComponent,
    SharedModule
  ],
  templateUrl: './teacher-personal-info.component.html',
  standalone: true
})
export class TeacherPersonalInfoComponent implements OnInit {
  teacherToSave:TeacherForm = {};
  teacherForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增教师信息'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(FacultySelectorComponent, { static: false }) facultySelectorComponent!: FacultySelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private teacherService: TeacherService
  ) {}

  ngOnInit(): void {
    this.teacherForm = this.fb.group({
      facultyId: [0],
      facultyName: ['', [Validators.required]],
      name: ['', [Validators.required]],
      password: ['', [Validators.required]],
      title: [undefined, [Validators.required]],
      gender: [undefined, [Validators.required]],
      contactPhone: ['', [Validators.required]],
      email: ['', [Validators.required]],
      profile: [''],
    })

    this.display(1)
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.teacherForm.controls) {
        this.teacherForm.controls[i].markAsDirty();
        this.teacherForm.controls[i].updateValueAndValidity();
      }
      if (!this.teacherForm.valid) {
        this.saveLoading = false
        return
      }
      this.teacherService.save(Object.assign(this.teacherToSave, this.teacherForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增教师信息'.slice()
    this.teacherForm.reset()
  }

  display(id: number) {
    this.saveLoading = true
    this.teacherService.findById(id).subscribe({
      next: (resp) => {
        if (resp && resp.code === 1 && resp.data) {
          this.teacherToSave = resp.data
          this.teacherForm.patchValue(this.teacherToSave);
        }
      },
      complete: () => {
        this.saveLoading = false
      }
    })
  }

  findFaculty() {
    this.facultySelectorComponent.display()
  }

  handleFacultySelectedEvent(selectedFaculty: { facultyId?: number; facultyName?: string; }) {
    if (selectedFaculty && 'facultyId' in selectedFaculty) {
      this.teacherForm.patchValue(selectedFaculty);
    }
  }
}

<nz-breadcrumb class="breadcrumb">
  <nz-breadcrumb-item>
    <a routerLink="/Home">主页</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>教师个人信息</nz-breadcrumb-item>
</nz-breadcrumb>
<form [formGroup]="teacherForm" (keydown.enter)="$event.preventDefault()">
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="facultyName" nzRequired>院系名称</nz-form-label>
        <nz-form-control [nzErrorTip]="'请选择院系名称'">
          <nz-input-group nzSearch [nzAddOnAfter]="facultyNameSuffixIconButton">
            <input nz-input formControlName="facultyName" placeholder="请选择院系名称" readonly />
          </nz-input-group>
          <ng-template #facultyNameSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findFaculty()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入姓名'">
          <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入密码'">
          <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="title" nzRequired>职称</nz-form-label>
        <nz-form-control [nzErrorTip]="'请选择职称'">
          <nz-select formControlName="title">
            <nz-option nzLabel="助教" [nzValue]="1"></nz-option>
            <nz-option nzLabel="讲师" [nzValue]="2"></nz-option>
            <nz-option nzLabel="副教授" [nzValue]="3"></nz-option>
            <nz-option nzLabel="教授" [nzValue]="4"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="gender" nzRequired>性别</nz-form-label>
        <nz-form-control [nzErrorTip]="'请选择性别'">
          <nz-select formControlName="gender">
            <nz-option nzLabel="男" [nzValue]="1"></nz-option>
            <nz-option nzLabel="女" [nzValue]="2"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="contactPhone" nzRequired>联系电话</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入联系电话'">
          <input nz-input formControlName="contactPhone" placeholder="请输入联系电话" maxlength="64"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
  <nz-row [nzGutter]="10">
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="email" nzRequired>邮箱</nz-form-label>
        <nz-form-control [nzErrorTip]="'请输入邮箱'">
          <input nz-input formControlName="email" placeholder="请输入邮箱" maxlength="64"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="11">
      <nz-form-item>
        <nz-form-label [nzSpan]="6" nzFor="profile">教师简介</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="profile" placeholder="请输入教师简介" maxlength="65535"/>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
</form>
<div class="form-button-container">
  <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
</div>
<faculty-selector (facultySelectedEvent)="handleFacultySelectedEvent($event)"></faculty-selector>

// v2_el/src/views/teacher/TeacherPersonalInfo.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form label-position="right" :model="teacherForm" :label-width="formLabelWidth" ref="refTeacherForm" :rules="rules">
        <el-row>
          <el-col :span="11">
            <el-form-item label="院系名称" prop="facultyName">
              <el-input v-model="teacherForm.facultyName" placeholder="请选择院系名称" readonly="readonly">
                <i slot="suffix" class="el-input__icon el-icon-search" @click="findFaculty"></i>
              </el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="teacherForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="密码" prop="password">
              <el-input v-model="teacherForm.password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="职称" prop="title">
              <el-select v-model="teacherForm.title" placeholder="请选择职称">
                <el-option label="助教" :value="1"></el-option>
                <el-option label="讲师" :value="2"></el-option>
                <el-option label="副教授" :value="3"></el-option>
                <el-option label="教授" :value="4"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="性别" prop="gender">
              <el-select v-model="teacherForm.gender" placeholder="请选择性别">
                <el-option label="男" :value="1"></el-option>
                <el-option label="女" :value="2"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="联系电话" prop="contactPhone">
              <el-input v-model="teacherForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="teacherForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="22">
            <el-form-item label="教师简介" prop="profile">
              <el-input v-model="teacherForm.profile" placeholder="请输入教师简介" type="textarea" :rows="5" maxlength="65535"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="facultySelectorVisible" v-if="facultySelectorVisible" title="院系信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <faculty-selector @faculty-selected-event="handleFacultySelectedEvent">
      </faculty-selector>
    </el-dialog>
  </div>
</template>

<script>
import teacherApi from '@/api/teacherApi'
import FacultySelector from "@/views/faculty/FacultySelector.vue";
export default {
  name: 'TeacherAdd',
  components: {FacultySelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      teacherForm: {
        facultyId: '',
        facultyName: '',
        name: '',
        password: '',
        title: '',
        gender: '',
        contactPhone: '',
        email: '',
        profile: ''
      },
      rules: {
        facultyName: [
          { required: true, message: '请输入院系名称', trigger: 'blur' }
        ],
        name: [
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '请输入密码', trigger: 'blur' }
        ],
        title: [
          { required: true, message: '请输入职称', trigger: 'blur' }
        ],
        gender: [
          { required: true, message: '请输入性别', trigger: 'blur' }
        ],
        contactPhone: [
          { required: true, message: '请输入联系电话', trigger: 'blur' }
        ],
        email: [
          { required: true, message: '请输入邮箱', trigger: 'blur' }
        ],
      },
      facultySelectorVisible: false,
    }
  },
  created () {
    teacherApi.findById(1)
        .then(resp => {
          if (resp && resp.code === 1) {
            this.teacherForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
  },
  methods: {
    onReset () {
      this.teacherForm = {
        facultyId: '',
        facultyName: '',
        name: '',
        password: '',
        title: '',
        gender: '',
        contactPhone: '',
        email: '',
        profile: ''
      }
      this.$emit('reset-teacher-add-event')
    },
    onSave () {
      this.$refs.refTeacherForm.validate((valid) => {
        if (valid) {
          teacherApi.save(this.teacherForm)
              .then((resp) => {
                if (resp && resp.code === 1) {
                  this.$message.success('保存成功')
                } else {
                  this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
                }
              })
              .catch(error => {
                console.log(error)
                this.$message.error('保存失败')
              })
        } else {
          return false
        }
      })
    },
    findFaculty () {
      this.facultySelectorVisible = true
    },
    handleFacultySelectedEvent (selectedFaculty) {
      this.facultySelectorVisible = false
      if (selectedFaculty && 'facultyId' in selectedFaculty && this.teacherForm.facultyId !== selectedFaculty['facultyId']) {
        this.teacherForm.facultyId = selectedFaculty['facultyId']
        this.teacherForm.facultyName = selectedFaculty['facultyName']
      }
    }
  }
}
</script>

<style lang="scss">
</style>
