// v3_el/src/views/StudentRegister.vue
<template>
  <div class="register-page">
    <div class="register">
      <div class="login-title">{{ $t('title') }}</div>
      <div class="login-subtitle">{{ $t('studentRegisterTitle') }}</div>
      <el-form :model="studentRegisterForm" :rules="rules" ref="studentRegisterFormRef" @keyup.enter.native="onRegister" label-width="80px">
        <el-row>
          <el-col :span="8">
            <el-form-item label="学号" prop="studentNumber">
              <el-input v-model="studentRegisterForm.studentNumber" placeholder="请输入学号" maxlength="20"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="studentRegisterForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="性别" prop="gender">
              <el-select v-model="studentRegisterForm.gender" placeholder="请选择性别">
                <el-option label="男" :value="1"></el-option>
                <el-option label="女" :value="2"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="密码" prop="password">
              <el-input v-model="studentRegisterForm.password" type="password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item prop="password2" label="确认密码">
              <el-input v-model="studentRegisterForm.password2" type="password" placeholder="请确认确认密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="出生日期" prop="birthDate">
              <el-date-picker
                  v-model="studentRegisterForm.birthDate" type="date" placeholder="出生日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="专业名称" prop="majorName">
              <el-input v-model="studentRegisterForm.majorName" placeholder="请选择专业名称" readonly="readonly">
                <template #suffix>
                  <el-icon @click="findMajor"><Search/></el-icon>
                </template>
              </el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="年级" prop="grade">
              <el-input-number v-model="studentRegisterForm.grade" :min="2000" :max="2100"></el-input-number>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="入学日期" prop="enrollmentDate">
              <el-date-picker
                  v-model="studentRegisterForm.enrollmentDate" type="date" placeholder="入学日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="联系电话" prop="contactPhone">
              <el-input v-model="studentRegisterForm.contactPhone" placeholder="请输入联系电话" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="studentRegisterForm.email" placeholder="请输入邮箱" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="毕业日期" prop="graduationDate">
              <el-date-picker
                  v-model="studentRegisterForm.graduationDate" type="date" placeholder="毕业日期" value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="省/市/区">
              <el-cascader
                v-model="provinceCityArea"
                :options="provinceCityAreaOptions"
                :props="{ expandTrigger: 'hover', value: 'code', label: 'name' }"
                @change="handleChange"/>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item prop="verificationCode" label="验证码">
              <el-input v-model="studentRegisterForm.verificationCode" placeholder="请输入验证码"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item>
              <canvas id="captchaCanvas" width="150" height="50" @click="drawCaptcha"></canvas>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="8">
            <el-form-item label="家庭地址" prop="address">
              <el-input v-model="studentRegisterForm.address" placeholder="请输入家庭地址" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <div class="center-container">
              <el-button type="primary" @click="onRegister" :loading="loading">注册</el-button>
              <el-button @click="onReset">重置</el-button>
              <el-button type="primary" @click="onBack">返回登录</el-button>
            </div>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="footer">
      <span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span><a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a>
    </div>
    <el-dialog v-model="majorSelectorVisible" v-if="majorSelectorVisible" title="专业信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <major-selector @major-selected-event="handleMajorSelectedEvent">
      </major-selector>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {inject, onMounted, reactive, ref, toRefs} from 'vue';
import {useCaptcha} from '@/composables/useCaptcha'
import studentApi from '@/api/studentApi'
import MajorSelector from "@/views/major/MajorSelector.vue";
import {ElMessage, type FormInstance} from "element-plus";
import type {StudentRegisterForm} from "@/types/req/studentRegisterForm";
import areas from "@/locales/area.json";
import type {Result} from "@/types/result";
import {useRouter} from "vue-router";
import {Search} from "@element-plus/icons-vue";

const { generatedVerificationCode, drawCaptcha } = useCaptcha()

const studentRegisterFormRef = ref<FormInstance | null>(null);
let studentRegisterForm = reactive<StudentRegisterForm>({
  studentNumber: '',
  name: '',
  password: '',
  password2: '',
  gender: 1,
  birthDate: '',
  majorId: 0,
  majorName: '',
  grade: 0,
  contactPhone: '',
  email: '',
  province: '',
  city: '',
  area: '',
  address: '',
  enrollmentDate: '',
  graduationDate: '',
  verificationCode: ''
})
const provinceCityArea = ref<string[]>([])
const provinceCityAreaOptions = areas.provinces
const majorSelectorVisible = ref<boolean>(false)
const loading = ref<boolean>(false)

const rules = reactive({
  studentNumber: [
    { required: true, message: '请输入学号', trigger: 'blur' }
  ],
  name: [
    { required: true, message: '请输入姓名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' }
  ],
  password2: [
    { required: true, message: '请确认密码', trigger: 'blur' }
  ],
  gender: [
    { required: true, message: '请输入性别', trigger: 'blur' }
  ],
  birthDate: [
    { required: true, message: '请输入出生日期', trigger: 'blur' }
  ],
  majorName: [
    { required: true, message: '请输入专业名称', trigger: 'blur' }
  ],
  grade: [
    { required: true, message: '请输入年级', trigger: 'blur' }
  ],
  contactPhone: [
    { required: true, message: '请输入联系电话', trigger: 'blur' }
  ],
  email: [
    { required: true, message: '请输入邮箱', trigger: 'blur' }
  ],
  verificationCode: [
    { required: true, message: '验证码不能为空', trigger: 'blur' }
  ]
});
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')
const formLabelWidth = ref<string>('')
const router = useRouter()

onMounted(() => {
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string, formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
});

const onReset = () => {
  if (studentRegisterFormRef.value) {
    studentRegisterFormRef.value.resetFields()
  }
  provinceCityArea.value = []
}

const refreshCaptcha = () => {
  studentRegisterForm.verificationCode = ''
  drawCaptcha()
}

const onRegister = () => {
  if (!studentRegisterFormRef.value) {
    return
  }
  studentRegisterFormRef.value.validate(async (valid: boolean) => {
    if (valid) {
      if (studentRegisterForm.password !== studentRegisterForm.password2) {
        ElMessage.error('两次输入的密码不一致，请重新输入')
        studentRegisterForm.password = ''
        studentRegisterForm.password2 = ''
        refreshCaptcha()
        return
      }
      if (generatedVerificationCode.value.toLowerCase() !== studentRegisterForm.verificationCode.toLowerCase()) {
        ElMessage.error('验证码错误')
        refreshCaptcha()
        return
      }
      loading.value = true
      const resp: Result<void> = await studentApi.save(studentRegisterForm)
      if (resp && resp.code === 1) {
        ElMessage.success('注册成功')
        await router.push({ path: '/Login', query: {type: 3} })
      } else {
        ElMessage.error('注册失败:' + (resp.msg ? resp.msg : ''))
        refreshCaptcha()
        loading.value = false
      }
    }
  })
}

const findMajor = () => {
  majorSelectorVisible.value = true
}

const handleMajorSelectedEvent = (selectedMajor: any) => {
  majorSelectorVisible.value = false
  if (selectedMajor && 'majorId' in selectedMajor && studentRegisterForm.majorId !== selectedMajor['majorId']) {
    studentRegisterForm.majorId = selectedMajor['majorId']
    studentRegisterForm.majorName = selectedMajor['majorName']
  }
}

const handleChange = (value: string[]) => {
  if (value && value.length > 0) {
    studentRegisterForm.province = value[0]
  }
  if (value && value.length > 1) {
    studentRegisterForm.city = value[1]
  }
  if (value && value.length > 2) {
    studentRegisterForm.area = value[2]
  }
}

const onBack = () => {
  router.push({ path: '/Login', query: {type: 3} })
}

</script>

<style lang="scss">
@use "@/assets/register.scss";
</style>

// react_antd/src/pages/StudentRegister.tsx
import React, {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import type {Result} from '@/types/result'
import {Button, Cascader, CascaderProps, Col, DatePicker, Form, Input, InputNumber, message, Row, Select} from 'antd';
import Captcha from '@/components/Captcha';
import {useTranslation} from "react-i18next";
import '@/assets/styles/register.css'
import studentApi from "@/api/studentApi.ts";
import MajorSelector from "@/pages/major/MajorSelector.tsx";
import {Student} from "@/types/resp/student";
import type {AreaOption} from "@/types/areaOption.ts";
import areas from "@/locales/area.json";
import {generateCaptcha} from "@/utils/verificationCode.ts";


type MessageType = 'success' | 'warning' | 'error';

// 定义校验规则
const rules = {
  studentNumber: [
    { required: true, message: '请输入学号' }
  ],
  name: [
    { required: true, message: '请输入姓名' }
  ],
  password: [
    { required: true, message: '请输入密码' }
  ],
  password2: [
    { required: true, message: '请确认密码' }
  ],
  gender: [
    { required: true, message: '请输入性别' }
  ],
  birthDate: [
    { required: true, message: '请输入出生日期' }
  ],
  majorName: [
    { required: true, message: '请输入专业名称' }
  ],
  grade: [
    { required: true, message: '请输入年级' }
  ],
  contactPhone: [
    { required: true, message: '请输入联系电话' }
  ],
  email: [
    { required: true, message: '请输入邮箱' }
  ],
  verificationCode: [
    { required: true, message: '验证码不能为空' }
  ]
};

const initialStudentForm: Partial<Student> = {
  gender: 1,
  majorId: 0,
  grade: 2000
}

const StudentRegister: React.FC = () => {
  const navigate = useNavigate();

  const [messageApi, messageContextHolder] = message.useMessage();

  const openNotification = (messageType: MessageType, msg: string, onCloseCallback?: () => void) => {
    messageApi.open({
      type: messageType,
      content: msg,
      duration: 1,
      onClose: () => {
        if (onCloseCallback) {
          onCloseCallback(); // 如果提供了回调，则执行它
        }
      }
    });
  };

  const handleRegisterSuccess = (type: MessageType, msg: string) => {
    openNotification(type, msg, () => {
      navigate(`/Login?type=3` );
    });
  };
  const handleRegisterError = (type: MessageType, msg: string) => {
    openNotification(type, msg);
  };

  const { t } = useTranslation();
  const [form] = Form.useForm();
  const [studentForm] = useState(initialStudentForm)

  const [generatedCaptcha, setGeneratedCaptcha] = useState(generateCaptcha());

  const refreshCaptcha = () => {
    const newCaptcha = generateCaptcha();
    setGeneratedCaptcha(newCaptcha);
  };

  const handleRegister = async () => {
    try {
      await form.validateFields()
      const student2Save:Student = Object.assign(studentForm, form.getFieldsValue())
      if (student2Save.password !== student2Save.password2) {
        messageApi.error('两次输入的密码不一致，请重新输入')
        refreshCaptcha()
        student2Save.password = ''
        student2Save.password2 = ''
        form.setFieldsValue(student2Save);
        return
      }
      if (student2Save.verificationCode && student2Save.verificationCode.toUpperCase() !== generatedCaptcha.toUpperCase()) {
        openNotification('error', '验证码不正确')
        refreshCaptcha()
        student2Save.verificationCode = ''
        form.setFieldsValue(student2Save);
        return
      }

      const resp: Result<void> = await studentApi.save(student2Save)
      if (!resp || resp.code !== 1) {
        const errorMsg = resp && resp.msg ? resp.msg : '操作异常'
        handleRegisterError('error', errorMsg)
        refreshCaptcha()
        return
      }
      handleRegisterSuccess('success', '注册成功')
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    form.resetFields();
  };

  const onBack = () => {
    navigate(`/Login?type=3` );
  }

  const [majorSelectorVisible, setMajorSelectorVisible] = useState(false);
  const findMajor = () => {
    setMajorSelectorVisible(true);
  }
  const handleMajorSelected = (selectedMajor: { majorId?: number; majorName?: string; }) => {
    setMajorSelectorVisible(false)
    if (selectedMajor && 'majorId' in selectedMajor) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
        majorId: selectedMajor['majorId'],
        majorName: selectedMajor['majorName'],
      }));
    }
  };
  const handleCloseMajorSelector = () => {
    setMajorSelectorVisible(false)
  };

  const provinceCityAreaOptions: AreaOption[] = areas.provinces

  const onAreaChange: CascaderProps<AreaOption>['onChange'] = (value) => {
    if (value && value.length > 0 && typeof value[0] === 'string') {
      studentForm.province = value[0]
    }
    if (value && value.length > 1 && typeof value[1] === 'string') {
      studentForm.city = value[1]
    }
    if (value && value.length > 2 && typeof value[2] === 'string') {
      studentForm.area = value[2]
    }
  };

  return (
    <div className="register-page">
      {messageContextHolder}
      <div className="register">
        <div className="login-title">{t('title')}</div>
        <div className="login-subtitle">{t('studentRegisterTitle')}</div>
        <Form form={form} initialValues={initialStudentForm} labelCol={{span: 6}}>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="studentNumber" label="学号" rules={rules.studentNumber}>
                <Input maxLength={20} placeholder="请输入学号"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="name" label="姓名" rules={rules.name}>
                <Input maxLength={64} placeholder="请输入姓名"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="gender" label="性别" rules={rules.gender}>
                <Select placeholder="请选择性别" options={[
                  {value: 1, label: <span>男</span>},
                  {value: 2, label: <span>女</span>}
                ]}/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="password" label="密码" rules={rules.password}>
                <Input maxLength={255} placeholder="请输入密码"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="password2" label="确认密码" rules={rules.password2}>
                <Input maxLength={255} placeholder="请输入确认密码"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="birthDate" label="出生日期" rules={rules.birthDate}>
                <DatePicker/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="majorName" label="专业名称" rules={rules.majorName}>
                <Input.Search placeholder="请选择专业名称" onSearch={findMajor} readOnly={true}/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="grade" label="年级" rules={rules.grade}>
                <InputNumber min={2000} max={2100}/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="enrollmentDate" label="入学日期">
                <DatePicker/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="contactPhone" label="联系电话" rules={rules.contactPhone}>
                <Input maxLength={64} placeholder="请输入联系电话"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="email" label="邮箱" rules={rules.email}>
                <Input maxLength={64} placeholder="请输入邮箱"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="graduationDate" label="毕业日期">
                <DatePicker/>
              </Form.Item>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="provinceCityArea" label="省/市/区">
                <Cascader options={provinceCityAreaOptions} fieldNames={{label: "name", value: "code"}}
                          onChange={onAreaChange} placeholder="请选择省/市/区"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="verificationCode" label="验证码" rules={rules.verificationCode}>
                <Input maxLength={6} placeholder="请输入验证码"/>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Captcha captcha={generatedCaptcha} onRefresh={refreshCaptcha}/>
            </Col>
          </Row>
          <Row gutter={10}>
            <Col span={8}>
              <Form.Item name="address" label="家庭地址">
                <Input maxLength={255} placeholder="请输入家庭地址"/>
              </Form.Item>
            </Col>
          </Row>
        </Form>
        <div className="custom-footer">
          <Button type="primary" onClick={handleRegister}>注册</Button>
          <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
          <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>返回登录</Button>
        </div>
      </div>
      <div className="footer">
        <span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span>
        <a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a>
      </div>
      <MajorSelector visible={majorSelectorVisible} onMajorSelected={handleMajorSelected}
                     onCloseMajorSelector={handleCloseMajorSelector}/>
    </div>
  );
};

export default StudentRegister;
