// v2_el/src/views/grade/GradeAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="gradeForm" :label-width="formLabelWidth" ref="refGradeForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="课程名称" prop="courseName">
            <el-input v-model="gradeForm.courseName" placeholder="请选择课程名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findCourse"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="学生学号" prop="studentNumber">
            <el-input v-model="gradeForm.studentNumber" placeholder="请选择学生学号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStudent"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="成绩" prop="grade">
            <el-input-number v-model="gradeForm.grade" :precision="2" :step="0.1" :min="1" :max="999"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="courseSelectorVisible" v-if="courseSelectorVisible" title="课程信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <course-selector @course-selected-event="handleCourseSelectedEvent">
      </course-selector>
    </el-dialog>
    <el-dialog :visible.sync="studentSelectorVisible" v-if="studentSelectorVisible" title="学生信息选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <student-selector @student-selected-event="handleStudentSelectedEvent">
      </student-selector>
    </el-dialog>
  </div>
</template>

<script>
import gradeApi from '@/api/gradeApi'
import CourseSelector from "@/views/course/CourseSelector.vue";
import StudentSelector from "@/views/student/StudentSelector.vue";
export default {
  name: 'GradeAdd',
  components: {CourseSelector,StudentSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      gradeForm: {
        courseId: '',
        courseName: '',
        studentId: '',
        studentNumber: '',
        grade: ''
      },
      rules: {
        courseName: [
          { required: true, message: '请输入课程名称', trigger: 'blur' }
        ],
        studentNumber: [
          { required: true, message: '请输入学生学号', trigger: 'blur' }
        ],
      },
      courseSelectorVisible: false,
      studentSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      gradeApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.gradeForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.gradeForm = {
        courseId: '',
        courseName: '',
        studentId: '',
        studentNumber: '',
        grade: ''
      }
      this.$emit('reset-grade-add-event')
    },
    onSave () {
      this.$refs.refGradeForm.validate((valid) => {
        if (valid) {
          gradeApi.save(this.gradeForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-grade-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findCourse () {
      this.courseSelectorVisible = true
    },
    handleCourseSelectedEvent (selectedCourse) {
      this.courseSelectorVisible = false
      if (selectedCourse && 'courseId' in selectedCourse && this.gradeForm.courseId !== selectedCourse['courseId']) {
        this.gradeForm.courseId = selectedCourse['courseId']
        this.gradeForm.courseName = selectedCourse['courseName']
      }
    },
    findStudent () {
      this.studentSelectorVisible = true
    },
    handleStudentSelectedEvent (selectedStudent) {
      this.studentSelectorVisible = false
      if (selectedStudent && 'studentId' in selectedStudent && this.gradeForm.studentId !== selectedStudent['studentId']) {
        this.gradeForm.studentId = selectedStudent['studentId']
        this.gradeForm.studentNumber = selectedStudent['studentNumber']
      }
    },
    onBack () {
      this.$emit('close-grade-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/grade/grade-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {GradeService} from '../../service/grade.service';
import {SharedModule} from '../shared.module';
import {GradeForm} from '../../types/req/GradeForm';
import {MODAL_WIDTH} from '../../const'
import {CourseSelectorComponent} from '../course/course-selector.component';
import {StudentSelectorComponent} from '../student/student-selector.component';

@Component({
  selector: 'grade-add',
  imports: [
    CourseSelectorComponent,
    StudentSelectorComponent,
    SharedModule
  ],
  templateUrl: './grade-add.component.html',
  standalone: true
})
export class GradeAddComponent implements OnInit {
  gradeToSave:GradeForm = {};
  gradeForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增成绩信息'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(CourseSelectorComponent, { static: false }) courseSelectorComponent!: CourseSelectorComponent;
  @ViewChild(StudentSelectorComponent, { static: false }) studentSelectorComponent!: StudentSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private gradeService: GradeService
  ) {}

  ngOnInit(): void {
    this.gradeForm = this.fb.group({
      courseId: [0],
      courseName: ['', [Validators.required]],
      studentId: [0],
      studentNumber: ['', [Validators.required]],
      grade: [0],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.gradeForm.controls) {
        this.gradeForm.controls[i].markAsDirty();
        this.gradeForm.controls[i].updateValueAndValidity();
      }
      if (!this.gradeForm.valid) {
        this.saveLoading = false
        return
      }
      this.gradeService.save(Object.assign(this.gradeToSave, this.gradeForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增成绩信息'.slice()
    this.gradeForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改成绩信息'
      this.saveLoading = true
      this.gradeService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.gradeToSave = resp.data
            this.gradeForm.patchValue(this.gradeToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findCourse() {
    this.courseSelectorComponent.display()
  }

  handleCourseSelectedEvent(selectedCourse: { courseId?: number; courseName?: string; }) {
    if (selectedCourse && 'courseId' in selectedCourse) {
      this.gradeForm.patchValue(selectedCourse);
    }
  }

  findStudent() {
    this.studentSelectorComponent.display()
  }

  handleStudentSelectedEvent(selectedStudent: { studentId?: number; studentNumber?: string; }) {
    if (selectedStudent && 'studentId' in selectedStudent) {
      this.gradeForm.patchValue(selectedStudent);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="gradeForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="courseName" nzRequired>课程名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择课程名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="courseNameSuffixIconButton">
                <input nz-input formControlName="courseName" placeholder="请选择课程名称" readonly />
              </nz-input-group>
              <ng-template #courseNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findCourse()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="studentNumber" nzRequired>学生学号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择学生学号'">
              <nz-input-group nzSearch [nzAddOnAfter]="studentNumberSuffixIconButton">
                <input nz-input formControlName="studentNumber" placeholder="请选择学生学号" readonly />
              </nz-input-group>
              <ng-template #studentNumberSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findStudent()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="grade">成绩</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="grade" [nzMin]="1" [nzMax]="999" [nzPrecision]="2" [nzStep]="0.1" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<course-selector (courseSelectedEvent)="handleCourseSelectedEvent($event)"></course-selector>
<student-selector (studentSelectedEvent)="handleStudentSelectedEvent($event)"></student-selector>
