// angular_ngzorro/src/app/teacher/teacher-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {Teacher} from '../../types/resp/Teacher';

@Component({
  selector: 'teacher-view',
  imports: [
    SharedModule
  ],
  templateUrl: './teacher-view.component.html',
  standalone: true
})
export class TeacherViewComponent implements OnInit {
  teacherForm!: FormGroup;
  isVisible: boolean = false
  title: string = '教师信息详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.teacherForm = this.fb.group({
      facultyName: [''],
      name: [''],
      password: [''],
      title: [undefined],
      gender: [undefined],
      contactPhone: [''],
      email: [''],
      profile: [''],
      createTime: [''],
      modifyTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(teacher: Teacher) {
    this.isVisible = true
    this.teacherForm.patchValue(teacher);
    this.teacherForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="teacherForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="facultyName">院系名称</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="facultyName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name">姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="name" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password">密码</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="password" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="title">职称</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="title">
                <nz-option nzLabel="助教" [nzValue]="1"></nz-option>
                <nz-option nzLabel="讲师" [nzValue]="2"></nz-option>
                <nz-option nzLabel="副教授" [nzValue]="3"></nz-option>
                <nz-option nzLabel="教授" [nzValue]="4"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="gender">性别</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="gender">
                <nz-option nzLabel="男" [nzValue]="1"></nz-option>
                <nz-option nzLabel="女" [nzValue]="2"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="contactPhone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="contactPhone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="email">邮箱</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="email" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="profile">教师简介</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="profile" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="modifyTime">最后修改时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="modifyTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/teacher/TeacherView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {Teacher} from "@/types/resp/teacher";

interface TeacherViewProps {
  visible: boolean;
  viewRow: object;
  onCloseTeacherView: () => void;
}

const TeacherView: React.FC<TeacherViewProps> = ({visible, viewRow, onCloseTeacherView}) => {

  const [form] = Form.useForm<Teacher>();

  const onBack = () => {
    onCloseTeacherView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"教师信息详情"} open={visible} onCancel={onCloseTeacherView} width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="facultyName" label="院系名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="name" label="姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="password" label="密码">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="title" label="职称">
              <Select placeholder="请选择职称" options={[
                { value: 1, label: <span>助教</span> },
                { value: 2, label: <span>讲师</span> },
                { value: 3, label: <span>副教授</span> },
                { value: 4, label: <span>教授</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="gender" label="性别">
              <Select placeholder="请选择性别" options={[
                { value: 1, label: <span>男</span> },
                { value: 2, label: <span>女</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="contactPhone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="email" label="邮箱">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="profile" label="教师简介">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={22}>
            <Form.Item name="profile" label="教师简介" labelCol={{span: 3}}>
              <Input.TextArea autoSize={{ minRows: 5, maxRows: 5 }}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default TeacherView;
